variable "grape_aws_account_id" {
  type        = string
  default     = "787587782604"
  description = "The AWS Account ID of the Grape Platform."
}

variable "external_id" {
  type        = string
  description = "Unique External ID generated by Grape to secure this connection."
}

variable "role_name" {
  type        = string
  default     = "GrapeProvisionerRole"
  description = "The name of the IAM role to be created."
}

resource "aws_iam_role" "grape_role" {
  name = "${var.role_name}-${var.external_id}"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          AWS = "arn:aws:iam::$${var.grape_aws_account_id}:root"
        }
        Condition = {
          StringEquals = {
            "sts:ExternalId" = var.external_id
          }
        }
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "admin_access" {
  role       = aws_iam_role.grape_role.name
  policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
}

output "role_arn" {
  value       = aws_iam_role.grape_role.arn
  description = "The ARN of the created Role. Please copy this back to the Grape dashboard."
}