// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * The shared paging vocabulary for CLI list routes — the server half.
 *
 * ONE shape, both sides. `pageInfoSchema` below is the single definition of the `page`
 * object every paged list response carries; `packages/core/api/paging.go` mirrors it as
 * `PageInfo`, and the two are locked together by the generated fixture
 * `packages/core/api/testdata/page_info.json` (regenerated by
 * `pnpm -C apps/console run gen:cli-fixtures`, diff-gated in CI, strict-decoded by the Go
 * side). Change the schema
 * here and the fixture moves; the Go decode then names the field that drifted.
 *
 * WHY CURSORS AND NOT OFFSETS. `/api/jobs` was the one endpoint that paginated, and it did it
 * with `limit`/`offset`; it is the first route converted onto this vocabulary (#3672) and still
 * accepts `?offset=` while the CLI's own pager is rewritten. Under a queue that inserts at the
 * head — which is what the
 * jobs table is — offset paging shows the same row on two consecutive pages every time a job
 * is enqueued mid-walk, and hides a row every time one is deleted. A keyset cursor over
 * `(created_at DESC, id DESC)` cannot: each page asks for rows strictly *below* a fixed
 * position, so a row inserted above the cursor is simply not in the remaining pages. That is
 * the property the integration suite proves against real Postgres, not the shape of the JSON.
 *
 * WHAT A CURSOR CARRIES, AND WHY IT IS NOT A DATE. `timestamptz` is microsecond precision and a
 * JS `Date` is millisecond precision, so a cursor minted from the row object drops rows — see
 * {@link CursorPosition}, which is the first thing to read before adopting any of this. Select
 * {@link cursorKey}, not the column.
 *
 * WHY THE TOTAL IS CAPPED. An exact `count(*)` over a large org's jobs is a full scan on every
 * page render. `countScoped` counts at most `cap + 1` rows and reports `mode: "capped"` when it
 * hit the ceiling, so `total` is then a FLOOR (`≥ total`) and the renderer says "1000+" rather
 * than lying with a precise-looking number. Under the cap it reports `mode: "exact"` and the
 * total is the true count. A renderer that ignores `mode` and prints `total` is wrong in
 * exactly one direction, which is why the field is not optional.
 *
 * WHAT LIVES WHERE. This module is the SERVER vocabulary: parse the request, scope the count,
 * build the response. Walking a cursor to exhaustion is a CLIENT act and has exactly one
 * implementation, `AllPages` in `packages/core/api/paging.go`. There is deliberately no TS
 * twin — a second walker is a second set of termination bugs.
 */

import { createHash } from "node:crypto";
import { and, count, type SQL, sql } from "drizzle-orm";
import type { PgColumn, PgTable } from "drizzle-orm/pg-core";
import { z } from "zod";
import type { Db, Tx } from "@/lib/db";

/** Page size used when the caller names none. */
export const DEFAULT_PAGE_SIZE = 50;

/** Ceiling on `?limit=`. A larger request is clamped, and `page.limit` echoes what was served. */
export const MAX_PAGE_SIZE = 200;

/**
 * How far `countScoped` will count before giving up and reporting a floor. 1000 is chosen so
 * that the overwhelming majority of orgs get an exact total, and the ones that do not are the
 * ones where an exact total was never worth a full scan.
 */
export const DEFAULT_COUNT_CAP = 1000;

/** Cursor envelope version. Bumping it invalidates every cursor in flight, by design. */
const CURSOR_VERSION = 1;

/**
 * The exact shape {@link cursorKey} renders: `2026-09-01T12:00:00.123456Z`. Six fractional digits,
 * because `timestamptz` is microsecond precision and three would silently drop rows.
 *
 * Shape only — {@link isCursorKey} also round-trips the value, which is what rejects a
 * well-shaped impossibility like `2026-02-30T…`. `Date.parse` does NOT reject that one (it rolls
 * over to March 2), and neither does an hour of `24`; measured, not assumed. Left unchecked they
 * reach Postgres as a caller-supplied value that raises, turning a 400 into a 500.
 */
const CURSOR_KEY_SHAPE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}Z$/;

/** The SQL type this vocabulary's cursors can carry as their tiebreak. See {@link paginate}. */
const SUPPORTED_ID_SQL_TYPE = "uuid";

/**
 * Projects a row's ordering column as the exact text a cursor carries.
 *
 * SELECT THIS, NOT THE COLUMN. `to_char` at UTC renders all six fractional digits and is
 * independent of the session `TimeZone`, and casting the result back with `::timestamptz` is
 * exact — verified against Postgres 17, both directions. Reading the column normally hands you a
 * JS `Date`, which has already lost the microseconds by the time any code here can see it, and
 * the loss is invisible: see {@link CursorPosition}.
 */
export function cursorKey(createdAt: PgColumn): SQL<string> {
	return sql<string>`to_char(${createdAt} at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')`;
}

/**
 * True when `value` is a cursor key that names a real instant.
 *
 * The round trip is the calendar check: rendering the parsed date back and comparing the
 * millisecond prefix catches every field that rolls over (`2026-02-30` → March 2, `24:00:00` →
 * the next day) rather than failing to parse.
 */
function isCursorKey(value: string): boolean {
	if (!CURSOR_KEY_SHAPE.test(value)) return false;
	const parsed = new Date(value);
	if (Number.isNaN(parsed.getTime())) return false;
	return parsed.toISOString().slice(0, 23) === value.slice(0, 23);
}

/** True when `value` is a canonical UUID — the only id kind a cursor can carry today. */
function isUuid(value: string): boolean {
	return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(
		value,
	);
}

/**
 * How to read `total`.
 *
 * - `exact`  — `total` is the true number of rows matching the scope.
 * - `capped` — the count stopped at the cap; `total` is a floor and the real number is ≥ it.
 */
export const pageModeSchema = z.enum(["exact", "capped"]);
export type PageMode = z.infer<typeof pageModeSchema>;

/**
 * The `page` object every paged CLI list response carries. Mirrored by `api.PageInfo` in
 * `packages/core/api/paging.go`; snake_case because the whole CLI wire contract is.
 *
 * `next_cursor` is `null` at exhaustion and nothing else — there is no separate `has_more`,
 * because two fields that must agree are two fields that can disagree.
 */
export const pageInfoSchema = z.object({
	mode: pageModeSchema,
	limit: z.number().int().positive(),
	total: z.number().int().nonnegative(),
	next_cursor: z.string().nullable(),
});
export type PageInfo = z.infer<typeof pageInfoSchema>;

/**
 * A cursor's binding. `orgId` is the tenancy scope the cursor was minted under and `list` names
 * the collection it walks, so a cursor cannot be replayed against another org (a 400, never
 * another tenant's page) or against another endpoint (a nonsense page rather than an error).
 *
 * This is belt to the route's own `eq(table.org_id, actor.orgId)` braces: the position inside a
 * cursor is never a scope, only an offset within one.
 */
export interface CursorScope {
	readonly orgId: string;
	readonly list: string;
}

/**
 * A position in the `(created_at DESC, id DESC)` ordering.
 *
 * `createdAt` IS A STRING, AND A JS `Date` IS NOT ACCEPTABLE HERE. `timestamptz` is microsecond
 * precision and a `Date` is millisecond precision, and drizzle's `timestamp` column maps to a
 * `Date` — so a cursor minted from the row object names an instant strictly EARLIER than the row
 * it came from, and every row in the gap between the two is excluded from the next page and from
 * every page after it. Silently: `next_cursor` and exhaustion both look normal, the walk is just
 * short. Demonstrated on Postgres 17 — rows at `.002500`, `.002100`, `.001000`, a page boundary
 * after the first, and a millisecond cursor returns `.001000` alone.
 *
 * So the key is the text {@link cursorKey} projects, carried through unchanged and handed back to
 * Postgres as a `timestamptz`. Round-trip exact, microseconds included.
 *
 * The id is the tiebreak, and it is not optional either: two rows written in the same microsecond
 * are ordinary in a batch enqueue, and without the tiebreak a page boundary between them either
 * repeats one or loses one.
 */
export interface CursorPosition {
	readonly createdAt: string;
	readonly id: string;
}

/** Parsed, validated paging inputs. `after` is null on the first page. */
export interface PageOpts {
	readonly limit: number;
	readonly after: CursorPosition | null;
}

/** A capped count and how to read it. */
export interface CountResult {
	readonly total: number;
	readonly mode: PageMode;
}

/** Why a cursor was refused. Both are 400s; they are distinguished so the message can be. */
export type CursorRejection = "malformed" | "foreign-scope";

export type CursorResult =
	| { readonly ok: true; readonly position: CursorPosition }
	| { readonly ok: false; readonly reason: CursorRejection };

export type PageOptsResult =
	| { readonly ok: true; readonly opts: PageOpts }
	| { readonly ok: false; readonly error: string };

/** The decoded cursor envelope. Parsed, never trusted — `s` is checked against the caller's scope. */
const cursorEnvelopeSchema = z.object({
	v: z.literal(CURSOR_VERSION),
	s: z.string().min(1),
	t: z.string().refine(isCursorKey),
	i: z.string().refine(isUuid),
});

/**
 * Fingerprints a cursor scope. Not a secret and not a signature — a cursor carries no
 * authority, so there is nothing to forge. It exists so that a cursor presented under the
 * wrong org or the wrong list is REFUSED rather than silently answered with a page the caller
 * did not ask for.
 */
function fingerprint(scope: CursorScope): string {
	// NUL as the separator, written as an escape rather than pasted as a byte — a raw NUL in a
	// source file makes git treat it as binary, so the module stops diffing and stops merging.
	// It separates rather than concatenates: with a joinable separator, {org: "a", list: "bc"}
	// and {org: "ab", list: "c"} would fingerprint identically, and one org's cursor would be
	// accepted by another's list.
	return createHash("sha256")
		.update(`${scope.orgId}\u0000${scope.list}`)
		.digest("base64url")
		.slice(0, 16);
}

/**
 * Encodes a position into an opaque cursor bound to `scope`. Opaque on purpose: the CLI must
 * not be able to construct one, because a hand-built cursor is a hand-built ordering
 * assumption that the server would then be obliged to keep.
 */
export function encodeCursor(
	scope: CursorScope,
	position: CursorPosition,
): string {
	// Both throws are SERVER bugs, not caller input, and they land where the cursor is MINTED —
	// on page 1, in the author's first test — rather than as a 400 the next request cannot get
	// past. A key that is not what cursorKey() projects means the route selected the column
	// instead of the projection and has already lost the microseconds; an id that is not a uuid
	// means the collection's key is not one this vocabulary can carry, and the decoder on the
	// other side of the round trip would refuse it.
	if (!isCursorKey(position.createdAt)) {
		throw new Error(
			`encodeCursor: "${position.createdAt}" is not a cursorKey() value (YYYY-MM-DDTHH:MM:SS.ssssssZ); select cursorKey(<column>) rather than the column`,
		);
	}
	if (!isUuid(position.id)) {
		throw new Error(
			`encodeCursor: cursor ids must be uuids, got "${position.id}"`,
		);
	}
	const envelope = {
		v: CURSOR_VERSION,
		s: fingerprint(scope),
		t: position.createdAt,
		i: position.id,
	};
	return Buffer.from(JSON.stringify(envelope), "utf8").toString("base64url");
}

/**
 * Decodes a cursor and checks it was minted for `scope`. Every failure path — bad base64, bad
 * JSON, a wrong version, an unparseable timestamp, another org's fingerprint — lands on a
 * rejection; none of them fall through to "no cursor", because a silently ignored cursor
 * restarts the walk from the top and duplicates every row already seen.
 */
export function decodeCursor(scope: CursorScope, raw: string): CursorResult {
	let parsed: unknown;
	try {
		parsed = JSON.parse(Buffer.from(raw, "base64url").toString("utf8"));
	} catch {
		return { ok: false, reason: "malformed" };
	}
	const envelope = cursorEnvelopeSchema.safeParse(parsed);
	if (!envelope.success) return { ok: false, reason: "malformed" };
	if (envelope.data.s !== fingerprint(scope)) {
		return { ok: false, reason: "foreign-scope" };
	}
	return {
		ok: true,
		position: { createdAt: envelope.data.t, id: envelope.data.i },
	};
}

/**
 * Parses `?limit=` and `?cursor=` for `scope`.
 *
 * `limit` must be a positive integer if present; a larger value is clamped to
 * {@link MAX_PAGE_SIZE} rather than refused, and `page.limit` reports what was actually
 * served. A missing or empty `cursor` is the first page — `?cursor=` is what a client that
 * builds its query string from an empty variable sends, and treating it as malformed would
 * fail the very first call of a walk.
 */
export function parsePageOpts(
	params: URLSearchParams,
	scope: CursorScope,
): PageOptsResult {
	const rawLimit = params.get("limit");
	let limit = DEFAULT_PAGE_SIZE;
	if (rawLimit !== null && rawLimit !== "") {
		if (!/^\d+$/.test(rawLimit)) {
			return { ok: false, error: "limit must be a positive integer" };
		}
		const parsed = Number(rawLimit);
		if (parsed < 1) {
			return { ok: false, error: "limit must be a positive integer" };
		}
		limit = Math.min(parsed, MAX_PAGE_SIZE);
	}

	const rawCursor = params.get("cursor");
	if (rawCursor === null || rawCursor === "") {
		return { ok: true, opts: { limit, after: null } };
	}
	const decoded = decodeCursor(scope, rawCursor);
	if (!decoded.ok) {
		return {
			ok: false,
			error:
				decoded.reason === "foreign-scope"
					? "cursor was issued for a different list or organization"
					: "cursor is malformed",
		};
	}
	return { ok: true, opts: { limit, after: decoded.position } };
}

/**
 * The number of rows a page query must ask for: one more than the page size, so that the
 * presence of the extra row — and nothing else — decides whether there is a next page.
 *
 * A caller that fetches `opts.limit` rows instead gets `next_cursor: null` on a full page and
 * silently truncates the walk. {@link buildPage} throws if handed more than this many rows,
 * which catches the opposite mistake; it cannot detect the first one, so this helper exists to
 * make the `+ 1` impossible to forget rather than merely documented.
 */
export function pageFetchLimit(opts: PageOpts): number {
	return opts.limit + 1;
}

/**
 * The canonical page ordering, `created_at DESC NULLS LAST, id DESC NULLS LAST`. Exported as a
 * pair so a caller cannot pair {@link afterCursor}'s predicate with a different `ORDER BY` —
 * the predicate is only correct under this one.
 *
 * NULLS LAST IS NOT DECORATION, AND IT IS NOT DRIZZLE'S `desc()`. Postgres defaults a `DESC`
 * sort to NULLS FIRST, while `CREATE INDEX ... DESC` — the form drizzle emits, and the form
 * `idx_jobs_org_cursor` is in — is DESC NULLS LAST. Those two orderings are not
 * interchangeable to the planner even on a NOT NULL column. Measured on Postgres 17 against
 * the real index: `ORDER BY created_at DESC, id DESC` plans a Bitmap Heap Scan on the plain
 * org index followed by a **Sort**; adding NULLS LAST plans an Index Only Scan on the cursor
 * index with the keyset comparison as the Index Cond. Same rows, same cursor semantics, and
 * an index that does nothing. `tests/integration/cli-paging.test.ts` asserts the plan.
 */
export function pageOrder(createdAt: PgColumn, id: PgColumn): [SQL, SQL] {
	return [sql`${createdAt} desc nulls last`, sql`${id} desc nulls last`];
}

/**
 * The keyset predicate for the rows strictly after `position` in {@link pageOrder}, or
 * `undefined` on the first page (so it drops out of an `and(...)` unchanged).
 *
 * A ROW comparison, not `created_at < x OR (created_at = x AND id < y)`: the row form is what
 * a composite `(org_id, created_at DESC, id DESC)` index can serve as a single range scan.
 *
 * BOTH VALUES ARE BOUND AS TEXT AND CAST. A raw `sql` parameter carries no column encoder, so
 * handing postgres-js a `Date` here fails at bind time with `ERR_INVALID_ARG_TYPE` rather than
 * anywhere near this line; and an uncast uuid string meets a `uuid` column with no way to
 * resolve the comparison's type. Measured, not defensive.
 */
export function afterCursor(
	position: CursorPosition | null,
	createdAt: PgColumn,
	id: PgColumn,
): SQL | undefined {
	if (position === null) return undefined;
	return sql`(${createdAt}, ${id}) < (${position.createdAt}::timestamptz, ${position.id}::uuid)`;
}

/**
 * Counts the rows in a tenancy-scoped collection, stopping at `cap`.
 *
 * The scope predicates are a NON-EMPTY tuple, so "count this table" is not expressible: the
 * routes this serves read through `getServiceDb()`, which bypasses RLS, and there the org
 * boundary is the WHERE clause and nothing else. The first element is the scope; anything
 * after it may be `undefined` so the caller can splat optional filters in without a cast.
 *
 * The cap is applied to a subquery (`SELECT 1 ... LIMIT cap + 1`) rather than to the count, so
 * Postgres stops scanning at the ceiling instead of counting the whole table and discarding
 * the excess. `cap + 1` is what makes "exactly cap rows" reportable as exact.
 */
export async function countScoped(
	db: Db | Tx,
	table: PgTable,
	where: readonly [SQL, ...(SQL | undefined)[]],
	cap: number = DEFAULT_COUNT_CAP,
): Promise<CountResult> {
	const capped = db
		.select({ hit: sql`1` })
		.from(table)
		.where(and(...where))
		.limit(cap + 1)
		.as("capped_scan");
	const rows = await db.select({ n: count() }).from(capped);
	const n = rows[0]?.n ?? 0;
	return n > cap ? { total: cap, mode: "capped" } : { total: n, mode: "exact" };
}

/** The three things a page's rows query must use verbatim. Handed to {@link paginate}'s callback. */
export interface PageQuery {
	/**
	 * Scope predicates AND the keyset predicate, already combined. Typed nullable only because
	 * that is what drizzle's `and()` returns; with a non-empty scope tuple it never is.
	 */
	readonly where: SQL | undefined;
	/** {@link pageOrder} for this collection. */
	readonly orderBy: [SQL, SQL];
	/** {@link pageFetchLimit} — one more than the page size. */
	readonly limit: number;
}

/**
 * Runs one page: the rows, the capped total, and the next cursor.
 *
 * This is the composition every paged route uses, and it exists because the three ways to get
 * cursor paging subtly wrong are all in the composing, not in the pieces — fetching `limit`
 * rows instead of `limit + 1`, ordering by something the keyset predicate does not match, and
 * counting the remainder after the cursor instead of the collection. The caller supplies only
 * what it alone knows: which columns to project and which tables to join, through `rows`.
 *
 * `total` is the size of the collection being walked — the scope predicates, WITHOUT the
 * keyset. It therefore stays put as the caller pages, which is what a reader expects from a
 * count beside a table; a total that counted the remainder would tick down to zero and read as
 * rows disappearing.
 */
export async function paginate<T>(args: {
	readonly db: Db | Tx;
	readonly table: PgTable;
	readonly createdAt: PgColumn;
	/**
	 * The collection's primary key. Must be a `uuid` column — checked below, because the cursor
	 * codec validates ids as uuids and {@link afterCursor} casts them `::uuid`, and a mismatch
	 * would otherwise serve page 1 correctly and mint a cursor its own parser refuses.
	 */
	readonly id: PgColumn;
	/** Tenancy scope first, then any filters. See {@link countScoped} for why it is a tuple. */
	readonly scope: readonly [SQL, ...(SQL | undefined)[]];
	readonly cursor: CursorScope;
	readonly opts: PageOpts;
	readonly countCap?: number;
	/**
	 * Runs the page's rows query with the supplied {@link PageQuery}, verbatim. The projection
	 * MUST include `cursorKey(createdAt)` and hand it to `positionOf` — see
	 * {@link CursorPosition} for what selecting the column instead costs.
	 */
	readonly rows: (query: PageQuery) => Promise<readonly T[]>;
	readonly positionOf: (row: T) => CursorPosition;
}): Promise<{ items: T[]; page: PageInfo }> {
	// The one place the vocabulary's uuid assumption can be contradicted, checked before a row is
	// served rather than at the caller's second request. A collection keyed by text or bigint
	// needs a second cursor kind — the id would have to carry its SQL type through the envelope
	// so the decoder can validate it and afterCursor can cast it — and there is no such
	// collection in the schema today, so the assumption is stated here instead of generalised.
	const idType = args.id.getSQLType();
	if (idType !== SUPPORTED_ID_SQL_TYPE) {
		throw new Error(
			`paginate: cursor paging requires a ${SUPPORTED_ID_SQL_TYPE} key column, got ${idType}`,
		);
	}
	const query: PageQuery = {
		where: and(...args.scope, afterCursor(args.opts.after, args.createdAt, args.id)),
		orderBy: pageOrder(args.createdAt, args.id),
		limit: pageFetchLimit(args.opts),
	};
	const [rows, counted] = await Promise.all([
		args.rows(query),
		countScoped(args.db, args.table, args.scope, args.countCap),
	]);
	return buildPage({
		rows,
		opts: args.opts,
		scope: args.cursor,
		count: counted,
		positionOf: args.positionOf,
	});
}

/**
 * Trims the extra row off a page fetched with {@link pageFetchLimit} and builds its
 * {@link PageInfo}.
 *
 * Throws when handed more rows than `pageFetchLimit(opts)`: that means the query used a
 * different limit from the one in `opts`, and the cursor it would mint would point past rows
 * the caller never returned — a silent hole in the walk. Loud beats subtle.
 */
export function buildPage<T>(args: {
	readonly rows: readonly T[];
	readonly opts: PageOpts;
	readonly scope: CursorScope;
	readonly count: CountResult;
	readonly positionOf: (row: T) => CursorPosition;
}): { items: T[]; page: PageInfo } {
	const { rows, opts, scope, count: counted, positionOf } = args;
	if (opts.limit < 1) {
		// `parsePageOpts` refuses this, but PageOpts is a plain interface and a hand-built one
		// with limit 0 would build a page of no rows whose next_cursor is null — a walk that
		// terminates immediately and reports the collection as empty. Loud, not quiet.
		throw new Error(`buildPage: page size must be at least 1, got ${opts.limit}`);
	}
	if (rows.length > opts.limit + 1) {
		throw new Error(
			`buildPage: got ${rows.length} rows for a page of ${opts.limit}; the query must use pageFetchLimit(opts) (${opts.limit + 1})`,
		);
	}
	const hasMore = rows.length > opts.limit;
	const items = hasMore ? rows.slice(0, opts.limit) : [...rows];
	const last = items[items.length - 1];
	return {
		items,
		page: {
			mode: counted.mode,
			limit: opts.limit,
			total: counted.total,
			next_cursor:
				hasMore && last !== undefined
					? encodeCursor(scope, positionOf(last))
					: null,
		},
	};
}
