// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

package argocd

import (
	"context"
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/alethialabs-io/alethialabs/packages/core/categories"
	"github.com/alethialabs-io/alethialabs/packages/core/manifests"
	"github.com/alethialabs-io/alethialabs/packages/core/types"
)

// THE cross-language invariant, and the one that fails in total silence.
//
// The vault chart names its Service after the Helm release; ArgoCD's release name is the Application
// name, which is `addon-` + the console's install-spec id. So hetznerVaultReleaseHost is not a name
// anyone gets to choose here — it is a CONSEQUENCE of the id and namespace the console mapper
// emitted. Get it wrong and nothing errors: the bootstrap Job's requests resolve nowhere, ESO's
// store never goes Valid, and the whole kind is quietly undelivered behind a green ArgoCD.
//
// The fixture is generated by the REAL mapper, so reading the id and namespace back out of it checks
// the actual TS contract rather than a string retyped in Go.
func TestHetznerVaultHostAgreesWithTheGeneratedFixture(t *testing.T) {
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot locate this file")
	}
	path := filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "test", "e2e", "fixtures", "hetzner_data_services.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Skipf("generated fixture not present (%v)", err)
	}
	var fx struct {
		AddOns []struct {
			ID        string `json:"id"`
			Chart     string `json:"chart"`
			Namespace string `json:"namespace"`
		} `json:"addons"`
	}
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	found := 0
	for _, a := range fx.AddOns {
		if a.Chart != "vault" {
			continue
		}
		found++
		want := AddOnAppName(a.ID) + "." + a.Namespace + ".svc.cluster.local:8200"
		if hetznerVaultReleaseHost != want {
			t.Errorf("hetznerVaultReleaseHost = %q, but the console renders install spec %q into namespace %q, "+
				"which ArgoCD syncs as Helm release %q — so the Service is at %q. A mismatch does not error: it resolves "+
				"nowhere, and the only symptom is a ClusterSecretStore that never goes Valid",
				hetznerVaultReleaseHost, a.ID, a.Namespace, AddOnAppName(a.ID), want)
		}
		if a.Namespace != hetznerVaultNamespace {
			t.Errorf("the chart installs into namespace %q but the bootstrap Job, its RBAC and the state Secret all live in %q — "+
				"the Job would run in a namespace with no Vault in it", a.Namespace, hetznerVaultNamespace)
		}
	}
	if found != 1 {
		t.Errorf("the fixture carries %d vault spec(s), want exactly 1 — every `secret` node on a project is a KV entry in the SAME Vault, "+
			"so a second release would be a second, unseeded, unreferenced Vault", found)
	}
}

func hetznerSecretProject(names ...string) *types.ProjectConfig {
	pc := &types.ProjectConfig{Provider: "hetzner"}
	for _, n := range names {
		pc.Secrets = append(pc.Secrets, types.ProjectSecretConfig{Name: n, Generate: true, Length: 32})
	}
	return pc
}

// THE naming invariant, and the one that fails silently.
//
// CleanupSkippedInfraServices reaps every name in categories.AllSaaSStoreNames() except the
// currently-selected connector's. `secretstore-vault` is in that set — it is the PLUGGABLE store for
// a Vault the CUSTOMER supplies. Naming the in-cluster store that would have it `kubectl delete`d on
// every deploy where no vault connector is chosen, and ESO would simply stop resolving with nothing
// in the job log to explain it.
func TestHetznerSecretStoreNameIsNotInTheSaaSReapSet(t *testing.T) {
	for _, name := range categories.AllSaaSStoreNames() {
		if name == HetznerSecretStoreName {
			t.Fatalf("the in-cluster store is named %q, which CleanupSkippedInfraServices reaps whenever "+
				"no matching SaaS connector is selected — pick a name outside AllSaaSStoreNames()", name)
		}
	}
	// It belongs to the per-cloud family instead, which is what it actually is.
	if !strings.HasPrefix(HetznerSecretStoreName, "secretstore-") {
		t.Errorf("store name %q leaves the per-cloud family convention", HetznerSecretStoreName)
	}
}

// A store in the per-cloud family MUST be in the esoStores reap map, or it is orphaned in a
// permanently-broken state when its Vault goes away — the exact failure that map exists to prevent.
func TestHetznerSecretStoreIsReapedWhenTheVaultIsGone(t *testing.T) {
	// Wired: the store renders, so it must NOT be reaped.
	keep := clusterSecretStoreRenderSet(&InfraFacts{Provider: "hetzner", HetznerInClusterVault: true})
	if !keep[HetznerSecretStoreName] {
		t.Error("the store does not render even though the in-cluster Vault is wired — it would be reaped")
	}
	// Not wired (no secret declared): it must be reaped rather than left pointing at nothing.
	drop := clusterSecretStoreRenderSet(&InfraFacts{Provider: "hetzner", HetznerInClusterVault: false})
	if drop[HetznerSecretStoreName] {
		t.Error("a store whose Vault is absent still renders — it would sit permanently broken")
	}
	// And on another cloud it is never rendered, so it is always reaped there.
	other := clusterSecretStoreRenderSet(&InfraFacts{Provider: "aws", IRSAExternalSecretsArn: "arn:x"})
	if other[HetznerSecretStoreName] {
		t.Error("the hetzner store renders on aws")
	}
	// The store must be KNOWN to the reaper at all — a name absent from the set is never reaped,
	// which is the orphan case this map exists to prevent.
	if _, known := drop[HetznerSecretStoreName]; !known {
		t.Error("the store is not in the reap set at all, so nothing would ever clean it up")
	}
}

func TestHetznerVaultForOnlyWhenHetznerAndSecretsExist(t *testing.T) {
	if got := HetznerVaultFor(hetznerSecretProject("api-key")); got == nil || len(got.Secrets) != 1 {
		t.Fatalf("a hetzner project with a secret derived %v", got)
	}
	// A Vault nobody asked for costs volumes and an audit surface for nothing.
	if got := HetznerVaultFor(hetznerSecretProject()); got != nil {
		t.Errorf("a project with no secrets derived a Vault: %v", got)
	}
	for _, provider := range []string{"aws", "gcp", "azure", "alibaba"} {
		pc := hetznerSecretProject("api-key")
		pc.Provider = types.CloudProvider(provider)
		if got := HetznerVaultFor(pc); got != nil {
			t.Errorf("%s derived an in-cluster Vault — it has a real cloud secret store", provider)
		}
	}
	if got := HetznerVaultFor(nil); got != nil {
		t.Errorf("a nil project derived %v", got)
	}
}

// These names interpolate into a rendered manifest and a container argument list.
func TestHetznerVaultForDropsUnsafeSecretNames(t *testing.T) {
	got := HetznerVaultFor(hetznerSecretProject("api-key", "Bad Name", "", "ok"))
	if got == nil || len(got.Secrets) != 2 {
		t.Fatalf("derived %v, want only the two safe names", got)
	}
	if got.Secrets[0].Name != "api-key" || got.Secrets[1].Name != "ok" {
		t.Errorf("derived %v", got.Secrets)
	}
}

// A secret routed to a PLUGGABLE store is read from that store through its own ClusterSecretStore.
// Minting it here too would put a second, different value under the same name — a split brain that
// surfaces as an application authenticating with the wrong credential, days later and nowhere near
// here. Every managed cloud already skips these (buildSecrets' secretProvisionedNatively).
func TestHetznerVaultForSkipsSecretsOwnedByAPluggableStore(t *testing.T) {
	pc := &types.ProjectConfig{Provider: "hetzner", Secrets: []types.ProjectSecretConfig{
		{Name: "ours", Generate: true},
		{Name: "theirs", Provider: "doppler", Generate: true},
		{Name: "explicit-native", Provider: "native", Generate: true},
	}}
	got := HetznerVaultFor(pc)
	if got == nil || len(got.Secrets) != 2 {
		t.Fatalf("derived %v, want the two natively-provisioned secrets", got)
	}
	for _, s := range got.Secrets {
		if s.Name == "theirs" {
			t.Error("a doppler-owned secret would ALSO be minted in the platform Vault — two values under one name")
		}
	}
	// And a project whose ONLY secret belongs to a connector needs no Vault at all.
	only := &types.ProjectConfig{Provider: "hetzner", Secrets: []types.ProjectSecretConfig{
		{Name: "theirs", Provider: "doppler"},
	}}
	if v := HetznerVaultFor(only); v != nil {
		t.Errorf("a project with only connector-owned secrets installed a Vault: %v", v)
	}
}

// THE offer-parity invariant. The canvas offers `generate`, `length` and `special_chars` on every
// cloud; the four managed ones carry all three into their secret store. Dropping them here would
// present three switches that change nothing — the state offer-parity refuses, and the state this
// file's first draft was in.
func TestHetznerVaultCarriesTheSizingTheCanvasOffers(t *testing.T) {
	pc := &types.ProjectConfig{Provider: "hetzner", Secrets: []types.ProjectSecretConfig{
		{Name: "api-key", Generate: true, Length: 64, SpecialChars: true},
		{Name: "operator-supplied"},
	}}
	got := HetznerVaultFor(pc)
	if got == nil || len(got.Secrets) != 2 {
		t.Fatalf("derived %v", got)
	}
	if got.Secrets[0] != (HetznerVaultSecret{Name: "api-key", Generate: true, Length: 64, SpecialChars: true}) {
		t.Errorf("the generated secret's sizing was dropped: %+v", got.Secrets[0])
	}
	if got.Secrets[1].Generate {
		t.Errorf("a manual secret was marked generated: %+v", got.Secrets[1])
	}

	// And it must survive the ONE channel to the Job, in the grammar the runner parses.
	y, err := HetznerVaultBootstrapJobManifest(*got, "runner:v1")
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	if !strings.Contains(y, "--secrets=api-key:64:1,operator-supplied:manual") {
		t.Errorf("the Job does not carry the declared sizing:\n%s", y)
	}
}

func TestHetznerVaultJobRefusesANegativeLength(t *testing.T) {
	bad := HetznerVault{Secrets: []HetznerVaultSecret{{Name: "api-key", Generate: true, Length: -1}}}
	if _, err := HetznerVaultBootstrapJobManifest(bad, "runner:v1"); err == nil {
		t.Error("rendered a Job asking for a negative-length secret")
	}
}

func TestHetznerVaultJobPassesEverySecretAndTheStoreCoordinates(t *testing.T) {
	y, err := HetznerVaultBootstrapJobManifest(HetznerVault{Secrets: []HetznerVaultSecret{{Name: "api-key", Generate: true}, {Name: "signing-key", Generate: true}}}, "runner:v1")
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	if !strings.Contains(y, "--secrets=api-key:0:0,signing-key:0:0") {
		t.Errorf("the Job does not carry both secret names:\n%s", y)
	}
	// The ESO credential the Job writes and the store's auth.secretRef must name the SAME Secret and
	// key, in the SAME namespace — a mismatch authenticates nothing and resolves nothing, silently.
	store := HetznerSecretStoreManifest()
	for _, want := range []string{HetznerSecretStoreCredSecret, hetznerSecretStoreCredKey, secretsSaaSNamespaceForStore} {
		if !strings.Contains(y, want) {
			t.Errorf("the Job does not mention %q", want)
		}
		if !strings.Contains(store, want) {
			t.Errorf("the ClusterSecretStore does not mention %q", want)
		}
	}
	// And the mount the bootstrap enables must be the path the store reads.
	if !strings.Contains(store, `path: "`+hetznerVaultKVMount+`"`) {
		t.Errorf("the store does not read the mount the bootstrap enables:\n%s", store)
	}
}

// A cluster-scoped store with no conditions is referenceable from ANY namespace, so on a shared
// Fabric a placed tenant could read the owner's secrets (#1306).
func TestHetznerSecretStoreDeniesPlacedTenantNamespaces(t *testing.T) {
	store := HetznerSecretStoreManifest()
	if !strings.Contains(store, "alethia.io/placement") || !strings.Contains(store, "NotIn") {
		t.Errorf("the store is not scoped away from placed tenant namespaces:\n%s", store)
	}
}

func TestHetznerVaultJobRefusesInvalidInput(t *testing.T) {
	good := HetznerVault{Secrets: []HetznerVaultSecret{{Name: "api-key", Generate: true}}}
	if _, err := HetznerVaultBootstrapJobManifest(good, ""); err == nil {
		t.Error("rendered a Job with no runner image")
	}
	if _, err := HetznerVaultBootstrapJobManifest(HetznerVault{}, "runner:v1"); err == nil {
		t.Error("rendered a Job with no secrets to seed")
	}
	bad := HetznerVault{Secrets: []HetznerVaultSecret{{Name: "api key\nfoo: bar"}}}
	if _, err := HetznerVaultBootstrapJobManifest(bad, "runner:v1"); err == nil {
		t.Error("rendered a Job with a secret name that would inject YAML")
	}
}

// No credential may reach the container through argv or env: argv is world-readable via /proc and
// env shows in `kubectl describe pod`. The Job carries only NAMES; every value is read or written
// through the Kubernetes API from inside the pod.
func TestHetznerVaultJobCarriesNoCredential(t *testing.T) {
	y, err := HetznerVaultBootstrapJobManifest(HetznerVault{Secrets: []HetznerVaultSecret{{Name: "api-key", Generate: true}}}, "runner:v1")
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	for _, forbidden := range []string{"secretKeyRef", "VAULT_TOKEN", "unsealKey", "--token"} {
		if strings.Contains(y, forbidden) {
			t.Errorf("the Job manifest mentions %q — no credential may reach the container this way:\n%s", forbidden, y)
		}
	}
	if !strings.Contains(y, "runAsNonRoot: true") || !strings.Contains(y, "readOnlyRootFilesystem: true") {
		t.Error("the Job pod is not hardened")
	}
	if strings.Contains(y, "ClusterRole") {
		t.Error("the bootstrap binds a ClusterRole — it must be namespace-scoped")
	}
}

func TestEnsureHetznerVaultIsANoOpWithNoVault(t *testing.T) {
	newKubectlStub(t, 0)
	if err := EnsureHetznerVault(context.Background(), nil, "runner:v1", io.Discard, io.Discard); err != nil {
		t.Errorf("a project with no in-cluster Vault errored: %v", err)
	}
}

func TestEnsureHetznerVaultDeletesTheStaleJobThenApplies(t *testing.T) {
	stub := newKubectlStub(t, 0)
	v := HetznerVaultFor(hetznerSecretProject("api-key"))

	if err := EnsureHetznerVault(context.Background(), v, "runner:v1", io.Discard, io.Discard); err != nil {
		t.Fatalf("EnsureHetznerVault: %v", err)
	}
	deleted, applied := -1, -1
	for i, c := range stub.calls() {
		if strings.Contains(c, "delete job") {
			deleted = i
		}
		if strings.Contains(c, "apply") {
			applied = i
		}
	}
	// Re-applying a completed Job fails on immutable fields, so without the delete a re-deploy never
	// re-runs the unseal step — and a Vault that restarted would stay sealed behind a green deploy.
	if deleted == -1 || applied == -1 || deleted > applied {
		t.Fatalf("calls = %v, want the stale Job deleted before the apply", stub.calls())
	}
}

func TestEnsureHetznerVaultReportsARenderFailure(t *testing.T) {
	newKubectlStub(t, 0)
	if err := EnsureHetznerVault(context.Background(), &HetznerVault{Secrets: []HetznerVaultSecret{{Name: "api-key", Generate: true}}}, "", io.Discard, io.Discard); err == nil {
		t.Error("rendered and applied a Job with no runner image")
	}
}

func TestEnsureHetznerVaultReportsAnApplyFailure(t *testing.T) {
	newKubectlStub(t, 0, stubRule{Match: "apply", Exit: 1})
	v := HetznerVaultFor(hetznerSecretProject("api-key"))
	if err := EnsureHetznerVault(context.Background(), v, "runner:v1", io.Discard, io.Discard); err == nil {
		t.Error("a failed apply was reported as success — Vault would stay sealed with nothing to say so")
	}
}

// ── the ClusterSecretStore apply ───────────────────────────────────────────────────────────────

// The store is applied on the SAME retry rail as the four cloud stores, and gated on the same fact
// that decides whether it is reaped. A store applied where no Vault exists points at a Service that
// is not there and sits permanently invalid; a store NOT applied where one does exist leaves the
// kind undelivered behind a green ArgoCD.
func TestEnsureHetznerSecretStoreIsGatedOnTheVaultFact(t *testing.T) {
	for name, facts := range map[string]*InfraFacts{
		"no facts at all":             nil,
		"hetzner with no Vault wired": {Provider: "hetzner"},
		"another cloud entirely":      {Provider: "aws", IRSAExternalSecretsArn: "arn:x"},
	} {
		// No kubectl on PATH: if it tried to apply, it would fail rather than return nil.
		t.Setenv("PATH", t.TempDir())
		var out strings.Builder
		if err := EnsureHetznerSecretStore(facts, &out, io.Discard); err != nil {
			t.Errorf("%s: applied a store anyway: %v", name, err)
		}
		if out.Len() != 0 {
			t.Errorf("%s: %q", name, out.String())
		}
	}
}

func TestEnsureHetznerSecretStoreReportsAnApplyFailure(t *testing.T) {
	t.Setenv("PATH", t.TempDir()) // no kubectl → the apply cannot succeed
	if err := EnsureHetznerSecretStore(
		&InfraFacts{Provider: "hetzner", HetznerInClusterVault: true}, io.Discard, io.Discard,
	); err == nil {
		t.Error("a failed apply was reported as success — ESO would resolve nothing with nothing in the log to say why")
	}
}

// The fact that gates the APPLY and the fact that gates the REAP must be the same one, or a deploy
// applies a store that the very next CleanupSkippedInfraServices deletes — an oscillation that reads
// as an intermittently-broken ESO.
func TestTheStoreApplyAndTheStoreReapReadTheSameFact(t *testing.T) {
	for _, wired := range []bool{true, false} {
		facts := &InfraFacts{Provider: "hetzner", HetznerInClusterVault: wired}
		if renders := clusterSecretStoreRenderSet(facts)[HetznerSecretStoreName]; renders != wired {
			t.Fatalf("HetznerInClusterVault=%v renders=%v — the reaper disagrees with the fact", wired, renders)
		}
		t.Setenv("PATH", t.TempDir())
		var out strings.Builder
		_ = EnsureHetznerSecretStore(facts, &out, io.Discard)
		attempted := out.Len() != 0
		if attempted != wired {
			t.Errorf("HetznerInClusterVault=%v: the apply %s while the reaper would %s it",
				wired, map[bool]string{true: "ran", false: "was skipped"}[attempted],
				map[bool]string{true: "keep", false: "delete"}[wired])
		}
	}
}

// The bootstrap Job writes the ESO token into a Secret; the store resolves that same Secret. This is
// asserted elsewhere on the rendered strings — here on the DERIVED facts, because HetznerVaultFor
// deciding the Vault exists and the store's gate disagreeing is the shape that would apply one
// without the other.
func TestTheVaultFactAndTheDerivedVaultAgree(t *testing.T) {
	pc := hetznerSecretProject("api-key")
	if (HetznerVaultFor(pc) != nil) != (BuildFromOutputs(map[string]interface{}{}, pc).HetznerInClusterVault) {
		t.Error("a project derives a Vault but the facts say there is none (or the reverse) — the Job and the store would disagree")
	}
	none := &types.ProjectConfig{Provider: "hetzner"}
	if BuildFromOutputs(map[string]interface{}{}, none).HetznerInClusterVault {
		t.Error("a project with no secret still sets HetznerInClusterVault — a store would be applied over an absent Vault")
	}
}

// PerCloudSecretStoreName must agree with the RENDERED manifest, which is the copy that can drift.
//
// The first version of this test compared the accessor against clusterSecretStoreRenderSet — and the
// same commit had just changed that map's keys to BE the accessor's output, so it was true by
// construction and only the empty-string branch could ever fire. The copy that can still drift is
// the hand-written literal in externalSecretsStoreTemplate: rename the template's store to
// `secretstore-gcp-native` and update the render tests alongside it (the natural edit) and the
// reaper would delete a store that no longer exists while orphaning the one that does, and the
// max-config probe would name a store that can never be Ready — a 40m timeout every gcp run.
//
// So this renders the real manifest per cloud with that cloud's identity facts populated and reads
// the name back out of it.
func TestPerCloudSecretStoreNameMatchesTheRenderedManifest(t *testing.T) {
	for _, tc := range []struct {
		provider string
		facts    *InfraFacts
	}{
		{"aws", &InfraFacts{Provider: "aws", Region: "us-east-1", IRSAExternalSecretsArn: "arn:aws:iam::1:role/eso"}},
		{"gcp", &InfraFacts{Provider: "gcp", GCPExternalSecretsSA: "eso@p.iam.gserviceaccount.com", GCPProjectID: "proj-1"}},
		{"azure", &InfraFacts{Provider: "azure", AzureExternalSecretsClient: "cid", AzureKeyVaultURI: "https://kv.vault.azure.net/"}},
		{"alibaba", &InfraFacts{Provider: "alibaba", Region: "eu-central-1", AlibabaExternalSecretsRoleArn: "acs:ram::1:role/eso"}},
	} {
		t.Run(tc.provider, func(t *testing.T) {
			m, err := externalSecretsStoreManifest(tc.facts)
			if err != nil {
				t.Fatalf("render: %v", err)
			}
			want := PerCloudSecretStoreName(tc.provider)
			if want == "" {
				t.Fatalf("PerCloudSecretStoreName(%q) is empty", tc.provider)
			}
			// The rendered document names the store on its own `name:` line. Anchored so a
			// *-xacct store cannot satisfy it.
			if !strings.Contains(m, "\n  name: "+want+"\n") {
				t.Errorf("the rendered ClusterSecretStore does not carry name %q — the accessor, the reaper "+
					"and the max-config probe would all be naming a store the template no longer renders.\n%s",
					want, m)
			}
		})
	}
	// Hetzner's store is rendered by a different path (the in-cluster Vault), so it is pinned by
	// TestHetznerSecretStoreNameIsNotInTheSaaSReapSet and the render set rather than here. What must
	// hold is that the accessor still answers for it.
	if PerCloudSecretStoreName("hetzner") != HetznerSecretStoreName {
		t.Errorf("PerCloudSecretStoreName(\"hetzner\") = %q, want %q",
			PerCloudSecretStoreName("hetzner"), HetznerSecretStoreName)
	}
	// A provider the platform does not run must return EMPTY rather than a plausible-looking name:
	// "secretstore-openstack" would read as real, and a probe naming it could never be Ready.
	if got := PerCloudSecretStoreName("openstack"); got != "" {
		t.Errorf("PerCloudSecretStoreName(\"openstack\") = %q, want \"\" — inventing a name for a cloud the "+
			"platform does not run produces a store that cannot exist", got)
	}
}

// The names have a SECOND exported accessor, and the two deliberately disagree on hetzner.
//
// manifests.StoreNameFor is what gets written into every workload's
// ExternalSecret.spec.secretStoreRef.name. It returns "" for hetzner where this one returns
// secretstore-hetzner, and both encode "empty means no per-cloud store" as load-bearing — so the two
// look interchangeable and give opposite answers on the one cloud where it matters. Consolidating
// onto the wrong one would emit ExternalSecrets against the Vault store for binding facets it cannot
// resolve, turning a loud "unsatisfiable, reported" into a silently never-syncing ExternalSecret.
//
// This pins both halves: they agree on the four managed clouds, and the hetzner divergence is
// intentional rather than drift.
func TestPerCloudSecretStoreNameAgreesWithManifestsStoreNameFor(t *testing.T) {
	for _, provider := range []string{"aws", "gcp", "azure", "alibaba"} {
		if got, want := manifests.StoreNameFor(provider), PerCloudSecretStoreName(provider); got != want {
			t.Errorf("manifests.StoreNameFor(%q) = %q but PerCloudSecretStoreName(%q) = %q — a workload's "+
				"secretStoreRef would name a store nothing renders", provider, got, provider, want)
		}
	}
	if manifests.StoreNameFor("hetzner") != "" {
		t.Errorf("manifests.StoreNameFor(\"hetzner\") = %q, want \"\" — hetzner's store is the in-cluster "+
			"Vault, which cannot resolve the cloud-secret-manager facets an ExternalSecret would ask it for; "+
			"if this is now intended, the divergence documented on PerCloudSecretStoreName must change too",
			manifests.StoreNameFor("hetzner"))
	}
}
