// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by apps/console/scripts/gen-go-validation.ts. DO NOT EDIT.
//
// Regenerate with: pnpm -C apps/console run gen:go-validation
//
// Every Step below is DATA. A Step names a rule; rules.go is the only place a name becomes
// behaviour, so nothing here — nor anything a server later publishes in this shape — can add
// code to the CLI. `Unshared` records the rules that deliberately did NOT cross over, with the
// reason, so a reader can tell a decision from an omission.

package validate

// intPtr keeps a legitimate 0 bound distinguishable from an unset one.
func intPtr(v int) *int { return &v }

// Specs is every field whose validation the console and the CLI share.
var Specs = map[string]Spec{
	"apps_path": {
		ID:       "apps_path",
		Why:      "project_repositories.apps_path — the apps-repo subpath a PLACED environment syncs. It lands verbatim in an ArgoCD Application's source.path, so argocd.ValidateAppsPath is the authority and this spec exists to say the same thing earlier.",
		Optional: true,
		Nullable: true,
		Steps: []Step{
			{Kind: StepTransform, Severity: SeverityReject, Message: "leading and trailing whitespace is ignored", Rule: "go_trim_space"},
			{Kind: StepMaxLength, Severity: SeverityReject, Message: "must be at most 512 characters", Length: intPtr(512)},
			{Kind: StepRule, Severity: SeverityReject, Message: "must be a repo-relative subpath such as overlays/dev (letters, digits, . _ - and /, no leading or trailing slash, no ..)", Rule: "apps_path"},
		},
	},
	"iac_var_key": {
		ID:  "iac_var_key",
		Why: "A BYO IaC variable name. The reserved alethia_ namespace was enforced only in Go, so the console stored alethia_project_id and the user then watched it vanish at apply.",
		Steps: []Step{
			{Kind: StepTransform, Severity: SeverityReject, Message: "leading and trailing whitespace is ignored", Rule: "js_trim"},
			{Kind: StepMinLength, Severity: SeverityReject, Message: "Variable name is required.", Length: intPtr(1)},
			{Kind: StepPattern, Severity: SeverityReject, Message: "Use a valid tfvar name (letters, digits, underscore).", Pattern: "^[A-Za-z_][A-Za-z0-9_]*$"},
			{Kind: StepRule, Severity: SeverityReject, Message: "Invalid variable name: the \"alethia_\" prefix is reserved for the platform context.", Rule: "not_reserved_tfvar_key"},
		},
	},
	"network_cidr_block.alibaba": {
		ID:  "network_cidr_block.alibaba",
		Why: "network.cidr_block on alibaba. cloud.validateNetworkCIDR refuses a network the template cannot carve its subnets out of, and nothing in the console checked this field at all — so the only feedback was a failed apply. Applies to a project that PROVISIONS ITS OWN network; the apply gate returns early for a brownfield one.",
		Steps: []Step{
			{Kind: StepPattern, Severity: SeverityReject, Message: "Enter a valid IPv4 CIDR, for example 10.0.0.0/16, or leave it blank for the template default.", Pattern: "^$|^(\\d{1,3}\\.){3}\\d{1,3}/\\d{1,3}$"},
			{Kind: StepRule, Severity: SeverityReject, Message: "This cloud carves its subnets out of the network with cidrsubnet(), so it needs a /28 or wider. Try 10.0.0.0/16.", Rule: "network_cidr_max_prefix", RuleArg: intPtr(28)},
		},
	},
	"network_cidr_block.aws": {
		ID:  "network_cidr_block.aws",
		Why: "network.cidr_block on aws. cloud.validateNetworkCIDR refuses a network the template cannot carve its subnets out of, and nothing in the console checked this field at all — so the only feedback was a failed apply. Applies to a project that PROVISIONS ITS OWN network; the apply gate returns early for a brownfield one.",
		Steps: []Step{
			{Kind: StepPattern, Severity: SeverityReject, Message: "Enter a valid IPv4 CIDR, for example 10.0.0.0/16, or leave it blank for the template default.", Pattern: "^$|^(\\d{1,3}\\.){3}\\d{1,3}/\\d{1,3}$"},
			{Kind: StepRule, Severity: SeverityReject, Message: "This cloud carves its subnets out of the network with cidrsubnet(), so it needs a /18 or wider. Try 10.0.0.0/16.", Rule: "network_cidr_max_prefix", RuleArg: intPtr(18)},
		},
	},
	"network_cidr_block.azure": {
		ID:  "network_cidr_block.azure",
		Why: "network.cidr_block on azure. cloud.validateNetworkCIDR refuses a network the template cannot carve its subnets out of, and nothing in the console checked this field at all — so the only feedback was a failed apply. Applies to a project that PROVISIONS ITS OWN network; the apply gate returns early for a brownfield one.",
		Steps: []Step{
			{Kind: StepPattern, Severity: SeverityReject, Message: "Enter a valid IPv4 CIDR, for example 10.0.0.0/16, or leave it blank for the template default.", Pattern: "^$|^(\\d{1,3}\\.){3}\\d{1,3}/\\d{1,3}$"},
			{Kind: StepRule, Severity: SeverityReject, Message: "This cloud carves its subnets out of the network with cidrsubnet(), so it needs a /18 or wider. Try 10.0.0.0/16.", Rule: "network_cidr_max_prefix", RuleArg: intPtr(18)},
		},
	},
	"network_cidr_block.gcp": {
		ID:  "network_cidr_block.gcp",
		Why: "network.cidr_block on gcp. cloud.validateNetworkCIDR refuses a network the template cannot carve its subnets out of, and nothing in the console checked this field at all — so the only feedback was a failed apply. Applies to a project that PROVISIONS ITS OWN network; the apply gate returns early for a brownfield one.",
		Steps: []Step{
			{Kind: StepPattern, Severity: SeverityReject, Message: "Enter a valid IPv4 CIDR, for example 10.0.0.0/16, or leave it blank for the template default.", Pattern: "^$|^(\\d{1,3}\\.){3}\\d{1,3}/\\d{1,3}$"},
			{Kind: StepRule, Severity: SeverityReject, Message: "Enter a valid IPv4 CIDR, for example 10.0.0.0/16.", Rule: "network_cidr_max_prefix", RuleArg: intPtr(32)},
		},
	},
	"network_cidr_block.hetzner": {
		ID:  "network_cidr_block.hetzner",
		Why: "network.cidr_block on hetzner. cloud.validateNetworkCIDR refuses a network the template cannot carve its subnets out of, and nothing in the console checked this field at all — so the only feedback was a failed apply. Applies to a project that PROVISIONS ITS OWN network; the apply gate returns early for a brownfield one.",
		Steps: []Step{
			{Kind: StepPattern, Severity: SeverityReject, Message: "Enter a valid IPv4 CIDR, for example 10.0.0.0/16, or leave it blank for the template default.", Pattern: "^$|^(\\d{1,3}\\.){3}\\d{1,3}/\\d{1,3}$"},
			{Kind: StepRule, Severity: SeverityReject, Message: "This cloud carves its subnets out of the network with cidrsubnet(), so it needs a /22 or wider. Try 10.0.0.0/16.", Rule: "network_cidr_max_prefix", RuleArg: intPtr(22)},
		},
	},
}
