// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by apps/console/scripts/gen-go-names.ts; DO NOT EDIT.
// Regenerate with: pnpm -C apps/console run gen:go-names
//
// The name grammar, mirrored from apps/console/lib/validations/names.ts. Every limit and every
// pattern here has exactly one definition, and it is the TypeScript one — the console owns these
// names because they are URL segments before they are anything else.

package names

import "regexp"

// SlugMaxLength is the DNS-1123 label limit, and therefore the slug limit.
const SlugMaxLength = 63

// NamespaceMaxLength is the longest name Kubernetes accepts for a Namespace.
const NamespaceMaxLength = 63

// NamespacePatternSource is Kubernetes' own DNS-1123 label grammar. Both surfaces compile this
// exact string; RE2 and JavaScript agree on it.
const NamespacePatternSource = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"

// NamespacePattern is NamespacePatternSource, compiled.
var NamespacePattern = regexp.MustCompile(NamespacePatternSource)

// EnvironmentNameMaxLength is the slug cap for an environment name — shorter than a DNS-1123
// label because the env name is a SEGMENT of longer derived names.
const EnvironmentNameMaxLength = 40

// EnvironmentNameInputMaxLength bounds the RAW name the rules will look at, measured in UTF-16
// code units (what JavaScript's String.prototype.length counts).
const EnvironmentNameInputMaxLength = 200

// AddOnAppNamePrefix is what argocd.AddOnAppName puts in front of an add-on id. It is part of the
// ArgoCD Application name's length budget, which is why it lives beside the cap.
const AddOnAppNamePrefix = "addon-"

// AddOnIDMaxLength is the cap for an add-on / BYO-chart id: the label limit minus the prefix, so
// that AddOnAppNamePrefix+id is still a legal Kubernetes name.
const AddOnIDMaxLength = 57

// ReservedEnvironmentNames are the environment names a console route would permanently shadow
// (/{org}/{project}/settings wins over an environment called "settings").
var ReservedEnvironmentNames = []string{
	"architecture",
	"settings",
	"jobs",
	"clusters",
	"usage",
	"environments",
}
