// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// Package names is the Go half of the one slugifier and the one name grammar (#3665).
//
// The console owns the algorithm — a slug is a URL segment before it is anything else — so this
// package is a MIRROR, not a second opinion. Its grammar constants are generated from
// apps/console/lib/validations/names.ts into names_gen.go, and its behaviour is held to
// testdata/name-cases.json, which is generated by running the REAL TypeScript implementation.
// Go cannot write that table, so a Go-only change has no way to make itself right.
//
// What it replaced, and why it mattered: five slugifiers disagreed. The Go two
// (argocd.ByoProjectName, argocd.namespaceTenantName) mapped every non-ASCII rune to a dash and
// then trimmed, so `café` became `caf` in Go and `cafe` in TypeScript — the console showed one
// name and the cluster got another. The TypeScript chartSlug had no length cap at all, and its
// output is prefixed into an ArgoCD Application name, which Kubernetes bounds at 63.
package names

import (
	"regexp"
	"strconv"
	"strings"

	"golang.org/x/text/unicode/norm"
)

// nonSlugRun matches a run of characters that is not a lowercase ASCII letter or digit — what
// collapses to a single dash. Mirrors the TypeScript `/[^a-z0-9]+/g`.
var nonSlugRun = regexp.MustCompile(`[^a-z0-9]+`)

// isCombiningMark reports whether r is in U+0300–U+036F, the Combining Diacritical Marks block.
//
// Deliberately the BLOCK and not unicode.Mn: the TypeScript twin strips exactly this range, and
// unicode.Mn is a strictly larger set (it includes, for example, the Devanagari and Hebrew marks).
// Stripping more than TypeScript does is how the two implementations would silently diverge again
// on the very inputs nobody tests by hand.
func isCombiningMark(r rune) bool { return r >= 0x0300 && r <= 0x036F }

// isApostrophe reports whether r is one of the quote characters that VANISH rather than becoming a
// dash, so `bob's` slugs to `bobs` and not `bob-s`. Mirrors the TypeScript `/['’ʼ`]+/g`.
func isApostrophe(r rune) bool {
	return r == '\'' || r == '’' || r == 'ʼ' || r == '`'
}

// utf16Len is len(s) as JavaScript measures it: UTF-16 code units, not bytes and not runes.
//
// It exists because every length rule in this package is generated from a TypeScript constant
// that was written against `String.prototype.length`. Using Go's byte length instead would make
// the two surfaces disagree about a 200-character limit as soon as the name contains an accent —
// which is exactly the class of drift this package was created to end.
func utf16Len(s string) int {
	n := 0
	for _, r := range s {
		if r > 0xFFFF {
			n += 2
		} else {
			n++
		}
	}
	return n
}

// SlugifyOrEmpty normalizes a free-text name into a slug, which MAY be empty.
//
// NFKD-folds accents (`José` → `jose`), drops apostrophes, collapses every other run of
// non-alphanumerics to a single dash, trims the ends, and caps at maxLength — re-trimming a
// trailing dash the cut exposes. A maxLength of zero or less means SlugMaxLength.
//
// Prefer Slugify. The empty return is the case that has to be handled, not the case to reach for.
func SlugifyOrEmpty(raw string, maxLength int) string {
	if maxLength <= 0 {
		maxLength = SlugMaxLength
	}
	var folded strings.Builder
	folded.Grow(len(raw))
	for _, r := range norm.NFKD.String(raw) {
		if isCombiningMark(r) || isApostrophe(r) {
			continue
		}
		folded.WriteRune(r)
	}
	s := strings.Trim(nonSlugRun.ReplaceAllString(strings.ToLower(folded.String()), "-"), "-")
	// s is now pure ASCII [a-z0-9-], so a byte slice is a character slice and matches what
	// JavaScript's String.prototype.slice would cut.
	if len(s) > maxLength {
		s = strings.TrimRight(s[:maxLength], "-")
	}
	return s
}

// Slugify normalizes a free-text name into a slug that is never empty: fallback is used (and is
// itself slugified and capped) when raw slugs away entirely.
//
// It PANICS when fallback also slugs to nothing, which is the same programmer error the
// TypeScript twin throws on. There is no honest value to return in that case, and returning ""
// is precisely the bug this signature exists to make impossible.
func Slugify(raw, fallback string, maxLength int) string {
	if s := SlugifyOrEmpty(raw, maxLength); s != "" {
		return s
	}
	if s := SlugifyOrEmpty(fallback, maxLength); s != "" {
		return s
	}
	panic("names.Slugify: fallback " + strconv.Quote(fallback) + " slugs to nothing; pass a fallback containing at least one letter or digit")
}

// legacyUnsafe is the charset filter that named the ArgoCD objects already applied in every
// customer cluster. It KEEPS existing hyphens (they are inside the allowed class) and therefore
// does not collapse runs, and it turns an apostrophe into a dash.
var legacyUnsafe = regexp.MustCompile(`[^a-z0-9-]+`)

// LegacyObjectSegment is FROZEN. It is the pre-#3665 derivation that named the ArgoCD AppProjects
// and Applications that are already applied — `argocd.ByoProjectName` and
// `argocd.namespaceTenantName` both fed a free-text project display name through it.
//
// It is deliberately NOT Slugify, and the difference is not cosmetic:
//
//	"Acme - Prod"    -> "acme---prod"   (Slugify: "acme-prod")
//	"Bob's Project"  -> "bob-s-project" (Slugify: "bobs-project")
//	"Foo--Bar"       -> "foo--bar"      (Slugify: "foo-bar")
//	"café"           -> "caf"           (Slugify: "cafe")
//
// Moving these two namers onto Slugify would give the console and the runner one answer, which is
// what #3665 is for — and it would also rename a live AppProject and Application on the next
// deploy, orphaning the existing pair, for every project whose display name contains an
// apostrophe, a spaced hyphen or a doubled hyphen. That is a MIGRATION, not a rename, so the rule
// lives here, once, under a name that says what it is, instead of as two copies of a regex.
//
// It has one definition rather than two so the census in gen-go-names.ts stays meaningful and the
// next reader finds the reason attached to the code rather than in a commit message.
func LegacyObjectSegment(s string) string {
	return strings.Trim(legacyUnsafe.ReplaceAllString(strings.ToLower(strings.TrimSpace(s)), "-"), "-")
}

// Bounded caps an already-slug-shaped name at SlugMaxLength, re-trimming a trailing dash the cut
// exposes. For names ASSEMBLED from parts — `addon-<id>`, `tenant-<project>-<namespace>` — where
// each part is within budget but the join is not.
func Bounded(name string) string {
	if len(name) <= SlugMaxLength {
		return name
	}
	return strings.TrimRight(name[:SlugMaxLength], "-")
}

// IsNamespace reports whether s is exactly what Kubernetes accepts as a Namespace name: a
// DNS-1123 label, at most NamespaceMaxLength characters.
func IsNamespace(s string) bool {
	return s != "" && utf16Len(s) <= NamespaceMaxLength && NamespacePattern.MatchString(s)
}

// NamespaceProblem returns why s is not a legal Kubernetes namespace, or "" when it is one. The
// message names the rule Kubernetes applies — the alternative is finding out at apply time.
func NamespaceProblem(s string) string {
	switch n := utf16Len(s); {
	case n == 0:
		return "Namespace is required"
	case n > NamespaceMaxLength:
		return "Namespace is " + strconv.Itoa(n) + " characters; Kubernetes allows at most " + strconv.Itoa(NamespaceMaxLength)
	case !NamespacePattern.MatchString(s):
		return "Namespace must be lowercase letters, digits or '-', and must start and end with a letter or digit"
	default:
		return ""
	}
}

// NormalizeEnvironmentName is the canonical form of an environment name — the slug that gets
// stored. Empty when the name slugs away entirely; EnvironmentNameProblem turns that into a message.
func NormalizeEnvironmentName(raw string) string {
	return SlugifyOrEmpty(raw, EnvironmentNameMaxLength)
}

// EnvironmentNameProblem returns why raw is unusable as an environment name, or "" when it is
// fine (possibly after normalization). The CLI may only ever reject what the server would
// certainly reject, and this is the server's rule, generated from it.
func EnvironmentNameProblem(raw string) string {
	if n := utf16Len(raw); n > EnvironmentNameInputMaxLength {
		return "Environment name is " + strconv.Itoa(n) + " characters; at most " + strconv.Itoa(EnvironmentNameInputMaxLength) + " are read"
	}
	name := NormalizeEnvironmentName(raw)
	if name == "" {
		return "Environment name must contain at least one letter or number"
	}
	for _, reserved := range ReservedEnvironmentNames {
		if name == reserved {
			return `"` + name + `" is reserved by the console and can't be used as an environment name`
		}
	}
	return ""
}
