// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// Generates Go constants for the enums the Go runner/CLI consume, from the drizzle
// enum SSOT (lib/db/schema/enums.ts). The Go side then references the generated
// constants instead of bare strings, so:
//   - REMOVING an enum value is a compile error at every Go use site (the constant
//     vanishes) — the same immediate break TypeScript would give.
//   - ADDING one is caught by the `exhaustive` linter (switches) + coverage tests
//     (maps), because AllX grows.
// CI runs this + `git diff --exit-code` so a stale generated file fails the build.
// Deterministic (schema order, no randomness) so the diff only fires on a real change.
// Run: pnpm -C apps/console run gen:go-enums

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
	addonMode,
	alertChannelType,
	alertSeverity,
	cacheEngine,
	chartWorkloadKind,
	cloudProvider,
	environmentStage,
	nosqlCapacityMode,
	nosqlKeyType,
	nosqlTableType,
	placementMode,
	projectStatus,
	provisionJobStatus,
	provisionJobType,
	serviceBindingFacet,
	serviceBindingKind,
	serviceWorkloadType,
	topicSubscriptionProtocol,
} from "@/lib/db/schema/enums";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, "../../../packages/core/types/enums_gen.go");

/** Enum value → PascalCase Go identifier segment (DESTROY_RUNNER → DestroyRunner). */
function pascal(value: string): string {
	return value
		.split(/[_-]/)
		.filter(Boolean)
		.map((s) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase())
		.join("");
}

/** English-ish plural for the `AllX` slice name (JobStatus → AllJobStatuses). */
function plural(name: string): string {
	return name.endsWith("s") ? `${name}es` : `${name}s`;
}

interface EnumSpec {
	typeName: string;
	dbName: string;
	values: readonly string[];
}

const ENUMS: EnumSpec[] = [
	{ typeName: "JobType", dbName: "provision_job_type", values: provisionJobType.enumValues },
	{ typeName: "JobStatus", dbName: "provision_job_status", values: provisionJobStatus.enumValues },
	{ typeName: "CloudProvider", dbName: "cloud_provider", values: cloudProvider.enumValues },
	{ typeName: "EnvironmentStage", dbName: "environment_stage", values: environmentStage.enumValues },
	{ typeName: "ProjectStatus", dbName: "project_status", values: projectStatus.enumValues },
	{ typeName: "PlacementMode", dbName: "placement_mode", values: placementMode.enumValues },
	{ typeName: "ServiceWorkloadType", dbName: "service_workload_type", values: serviceWorkloadType.enumValues },
	{ typeName: "ChartWorkloadKind", dbName: "chart_workload_kind", values: chartWorkloadKind.enumValues },
	{ typeName: "NosqlKeyType", dbName: "nosql_key_type", values: nosqlKeyType.enumValues },
	{ typeName: "NosqlTableType", dbName: "nosql_table_type", values: nosqlTableType.enumValues },
	{ typeName: "NosqlCapacityMode", dbName: "nosql_capacity_mode", values: nosqlCapacityMode.enumValues },
	{ typeName: "CacheEngine", dbName: "cache_engine", values: cacheEngine.enumValues },
	{ typeName: "ServiceBindingKind", dbName: "service_binding_kind", values: serviceBindingKind.enumValues },
	{ typeName: "ServiceBindingFacet", dbName: "service_binding_facet", values: serviceBindingFacet.enumValues },
	{ typeName: "TopicSubscriptionProtocol", dbName: "topic_subscription_protocol", values: topicSubscriptionProtocol.enumValues },
	{ typeName: "AddonMode", dbName: "addon_mode", values: addonMode.enumValues },
	{ typeName: "AlertChannelType", dbName: "alert_channel_type", values: alertChannelType.enumValues },
	{ typeName: "AlertSeverity", dbName: "alert_severity", values: alertSeverity.enumValues },
];

function renderEnum(e: EnumSpec): string {
	const names = e.values.map((v) => `${e.typeName}${pascal(v)}`);
	// Pad the const names to the widest so the output is gofmt-stable (gofmt aligns the
	// `=` column) — keeps the CI regen `git diff` from firing on formatting alone.
	const width = Math.max(...names.map((n) => n.length));
	const consts = e.values
		.map((v, i) => `\t${names[i].padEnd(width)} ${e.typeName} = ${JSON.stringify(v)}`)
		.join("\n");
	const all = names.map((n) => `\t${n},`).join("\n");
	return `// ${e.typeName} mirrors the ${e.dbName} enum (lib/db/schema/enums.ts).
type ${e.typeName} string

const (
${consts}
)

// All${plural(e.typeName)} is every ${e.dbName} value, in schema order.
var All${plural(e.typeName)} = []${e.typeName}{
${all}
}`;
}

const out = `// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by apps/console/scripts/gen-go-enums.ts; DO NOT EDIT.
// Regenerate with: pnpm -C apps/console run gen:go-enums
//
// These mirror the drizzle enum SSOT (apps/console/lib/db/schema/enums.ts). Reference
// the constants (not bare strings) in Go so a removed enum value fails to compile and a
// new one is caught by the exhaustive linter + coverage tests.

package types

${ENUMS.map(renderEnum).join("\n\n")}
`;

writeFileSync(outPath, out);
console.log(
	`wrote ${outPath} — ${ENUMS.map((e) => `${e.typeName}(${e.values.length})`).join(", ")}`,
);
