-- 1. Create clusters table (The Agent Identity)
CREATE TABLE IF NOT EXISTS public.clusters (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    status TEXT CHECK (status IN ('PENDING', 'ONLINE', 'OFFLINE')) DEFAULT 'PENDING',
    last_heartbeat TIMESTAMPTZ,
    agent_token_hash TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS for clusters
ALTER TABLE public.clusters ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own clusters" 
    ON public.clusters FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own clusters" 
    ON public.clusters FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own clusters" 
    ON public.clusters FOR UPDATE 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own clusters" 
    ON public.clusters FOR DELETE 
    USING (auth.uid() = user_id);


-- 2. Create provisions table (The Job Queue)
CREATE TABLE IF NOT EXISTS public.provisions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    cluster_id UUID REFERENCES public.clusters(id) ON DELETE CASCADE NOT NULL,
    
    -- The State to Apply
    config_snapshot JSONB NOT NULL,
    
    -- Job Lifecycle
    status TEXT CHECK (status IN ('QUEUED', 'PROCESSING', 'SUCCESS', 'FAILED', 'CANCELLED')) DEFAULT 'QUEUED',
    
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT now(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    
    -- Result Metadata
    error_message TEXT,
    execution_metadata JSONB
);

-- RLS for provisions
ALTER TABLE public.provisions ENABLE ROW LEVEL SECURITY;

-- Users can see provisions for their clusters
CREATE POLICY "Users can view provisions for their clusters" 
    ON public.provisions FOR SELECT 
    USING (
        EXISTS (
            SELECT 1 FROM public.clusters 
            WHERE clusters.id = provisions.cluster_id 
            AND clusters.user_id = auth.uid()
        )
    );

-- Users can create provisions for their clusters
CREATE POLICY "Users can create provisions for their clusters" 
    ON public.provisions FOR INSERT 
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.clusters 
            WHERE clusters.id = provisions.cluster_id 
            AND clusters.user_id = auth.uid()
        )
    );


-- 3. Create provision_logs table (The Feedback Loop)
CREATE TABLE IF NOT EXISTS public.provision_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provision_id UUID REFERENCES public.provisions(id) ON DELETE CASCADE NOT NULL,
    
    log_chunk TEXT NOT NULL,
    stream_type TEXT CHECK (stream_type IN ('STDOUT', 'STDERR', 'SYSTEM')) DEFAULT 'STDOUT',
    
    created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS for provision_logs
ALTER TABLE public.provision_logs ENABLE ROW LEVEL SECURITY;

-- Users can view logs for their provisions
CREATE POLICY "Users can view logs for their provisions" 
    ON public.provision_logs FOR SELECT 
    USING (
        EXISTS (
            SELECT 1 FROM public.provisions
            JOIN public.clusters ON clusters.id = provisions.cluster_id
            WHERE provisions.id = provision_logs.provision_id
            AND clusters.user_id = auth.uid()
        )
    );

-- Indexes for performance
CREATE INDEX idx_provisions_cluster_status ON public.provisions(cluster_id, status);
CREATE INDEX idx_provision_logs_provision_id ON public.provision_logs(provision_id);
