// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// The Go half of the formatter contract.
//
// `packages/format/conformance/format-cases.json` is generated by TypeScript from the real
// `@repo/format` implementation, over inputs a human curates. This file drives the SAME rows through
// the Go implementation and requires the same answers. The three layers, from the table's own header:
//
//	1. packages/format/tests/conformance.test.ts — TS changed and the table did not
//	2. the CI diff-gate                          — the table is stale
//	3. THIS FILE                                 — Go disagrees with the table
//
// Go cannot write the file, so it has no way to make itself right. Neither side drifts alone.
//
// NEVER run `pnpm -C apps/console run gen:format-conformance --write` to make this file go green. That is
// exactly what somebody does when a Go test is red, and it converts a disagreement into a silently
// rewritten expectation. If Go is wrong, fix Go. If the TABLE is wrong, change the TypeScript and
// let the generator move the row, where the changed-case summary shows it in review.

package format

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"time"
)

const tableRel = "packages/format/conformance/format-cases.json"

// regenerate is printed on every failure that could be a stale table rather than a real disagreement.
const regenerate = "If the TABLE is stale, regenerate it from TypeScript: pnpm -C apps/console run gen:format-conformance"

type tableFile struct {
	Version  int               `json:"version"`
	Excluded map[string]string `json:"excluded"`
	// ZeroDecimalCharge is the TypeScript side's zero-decimal CHARGE set, published verbatim from
	// `STRIPE_ZERO_DECIMAL_CHARGE` in packages/format/src/minor-units.ts (schema v2, #4123). It is
	// not a case section: it has no inputs and no expectation, it is the SET itself.
	ZeroDecimalCharge []string                    `json:"zeroDecimalCharge"`
	Cases             map[string][]map[string]any `json:"cases"`
}

// schemaVersion is the lowest table shape this file can be held to — the one that carries
// `zeroDecimalCharge`. Checked as a FLOOR rather than an equality: a later shape change bumps the
// version for a reason of its own and must not red this mirror for adding something Go ignores.
const schemaVersion = 2

// monorepoRoot walks up to the directory holding go.work. Returns "" outside a monorepo checkout, so
// packages/core stays vendorable standalone — the same escape secrets_runtime_read_mirror_test uses.
func monorepoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.work")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

func loadTable(t *testing.T) tableFile {
	t.Helper()
	root := monorepoRoot(t)
	if root == "" {
		// Vendored standalone. There is no table to drive, and that is not a failure.
		t.Skip("not a monorepo checkout — no conformance table to drive")
	}
	// The root EXISTS and the file does not: that IS a failure, and a different one.
	raw, err := os.ReadFile(filepath.Join(root, tableRel))
	if err != nil {
		t.Fatalf("read %s: %v\n%s", tableRel, err, regenerate)
	}
	var tbl tableFile
	if err := json.Unmarshal(raw, &tbl); err != nil {
		t.Fatalf("decode %s: %v\n%s", tableRel, err, regenerate)
	}
	return tbl
}

// num reads a numeric input. JSON `null` is the table's sentinel for "not a finite number" — NaN is
// not representable in JSON — so it decodes to NaN here, which is what the TS side passes too.
func num(t *testing.T, row map[string]any, key string) float64 {
	t.Helper()
	v, present := row[key]
	if !present {
		t.Fatalf("row %v has no %q", row["id"], key)
	}
	if v == nil {
		return math.NaN()
	}
	f, ok := v.(float64)
	if !ok {
		t.Fatalf("row %v: %q is %T, want a number", row["id"], key, v)
	}
	return f
}

func str(t *testing.T, row map[string]any, key string) string {
	t.Helper()
	v, ok := row[key].(string)
	if !ok {
		t.Fatalf("row %v: %q is %T, want a string", row["id"], key, row[key])
	}
	return v
}

// drivers unpack each section's row into a call. This is the whole contract: one line per section,
// mirroring DRIVERS in packages/format/tests/conformance.test.ts.
var drivers = map[string]func(*testing.T, map[string]any) string{
	"minutes":  func(t *testing.T, r map[string]any) string { return Minutes(num(t, r, "in")) },
	"quota":    func(t *testing.T, r map[string]any) string { return Quota(num(t, r, "used"), num(t, r, "included")) },
	"duration": func(t *testing.T, r map[string]any) string { return Duration(millis(num(t, r, "in"))) },
	"bytes":    func(t *testing.T, r map[string]any) string { return Bytes(num(t, r, "in")) },
	"money":    func(t *testing.T, r map[string]any) string { return Money(num(t, r, "cents"), str(t, r, "currency")) },
	"monthlyRate": func(t *testing.T, r map[string]any) string {
		return MonthlyRate(num(t, r, "amount"), RateStyle(str(t, r, "style")), str(t, r, "currency"))
	},
	"monthlyDelta": func(t *testing.T, r map[string]any) string {
		return MonthlyDelta(num(t, r, "amount"), RateStyle(str(t, r, "style")), str(t, r, "currency"))
	},
	"date": func(t *testing.T, r map[string]any) string {
		loc, err := time.LoadLocation(str(t, r, "timeZone"))
		if err != nil {
			// A zone the runtime cannot resolve is an environment fault, not a disagreement — and
			// it is the exact failure `_ "time/tzdata"` exists to prevent, so say so.
			t.Fatalf("row %v: LoadLocation(%q): %v — is `_ \"time/tzdata\"` still imported in format.go?",
				r["id"], str(t, r, "timeZone"), err)
		}
		raw, isString := r["value"].(string)
		if !isString {
			// The table's null-date case. Go has no nullable time, so the zero value carries it.
			return Date(time.Time{}, DateStyle(str(t, r, "style")), loc)
		}
		parsed, err := time.Parse(time.RFC3339, raw)
		if err != nil {
			// The table's unparseable-date case. The TS side hands `new Date` a string it cannot
			// read and gets the em dash; Go's caller cannot construct a time at all, so the zero
			// value stands in for the same thing.
			return Date(time.Time{}, DateStyle(str(t, r, "style")), loc)
		}
		return Date(parsed, DateStyle(str(t, r, "style")), loc)
	},
}

// millis converts the table's millisecond numbers to a Duration. NaN and negatives both land at or
// below zero, which is what the `nonfinite-clamps` and `negative-clamps` rows expect.
func millis(ms float64) time.Duration {
	if math.IsNaN(ms) || math.IsInf(ms, 0) {
		return 0
	}
	return time.Duration(ms) * time.Millisecond
}

func TestGoMatchesTheConformanceTable(t *testing.T) {
	tbl := loadTable(t)
	for _, problem := range tableProblems(tbl) {
		t.Fatal(problem)
	}

	for section, rows := range tbl.Cases {
		drive, ok := drivers[section]
		if !ok {
			continue // reported by tableProblems above; do not also fail per-row
		}
		for _, row := range rows {
			id, _ := row["id"].(string)
			want, _ := row["want"].(string)
			t.Run(id, func(t *testing.T) {
				if got := drive(t, row); got != want {
					t.Errorf("%s\n  got  %q\n  want %q\n%s", id, got, want, regenerate)
				}
			})
		}
	}
}

// ── the guard ──────────────────────────────────────────────────────────────────────────────────

// requiredIDs are the rows that exist because the two languages disagreed, or would. Named, NOT
// counted: a count floor is cleared by unrelated rows, so every case a guard protects can be deleted
// while the threshold still passes. That defect shipped twice in this repo before it was believed.
//
// Deliberately duplicated from packages/format/tests/conformance.test.ts rather than derived from
// the table: this is Go stating what it REQUIRES of a file TypeScript writes. A list generated from
// the table would be regenerated by the same command that removed the row.
var requiredIDs = []string{
	// Go's %.0f rounds half to EVEN; JavaScript rounds half away from zero. The reason this
	// package exists, and the reason cmd/clusters_list.go printed $12 for $12.50.
	"monthlyRate/estimate/HALF-CENT-ROUNDS-AWAY-FROM-ZERO",
	"monthlyRate/exact/HALF-CENT-ROUNDS-AWAY-FROM-ZERO",
	// Rounding happens once, BEFORE the hour test.
	"minutes/HALF-ROUNDS-UP-ACROSS-THE-HOUR-BOUNDARY",
	"minutes/the-0.943-bug",
	// The used side humanises; the allowance never does, and it keeps its separator.
	"quota/used-exceeds-allowance-is-not-clamped",
	"quota/ALLOWANCE-KEEPS-THOUSANDS-SEPARATOR",
	// The duration ruling, and the boundary in both directions.
	"duration/TWO-HOURS-ROLLS-INTO-HOURS",
	"duration/JUST-UNDER-AN-HOUR-DOES-NOT-ROLL",
	"duration/EXACTLY-AN-HOUR",
	// hourCycle h23, not hour12:false — the option that renders midnight as 24:00 in some locales.
	"date/MIDNIGHT-IS-00-NOT-24",
	// A zone that shifts the calendar day is the case `_ "time/tzdata"` is imported for.
	"date/zone-shifts-the-day",
	// A currency with no minor unit, and one whose symbol is not its ISO prefix.
	"monthlyRate/estimate/JPY-HAS-NO-MINOR-UNIT",
	"money/EUR-NARROW-SYMBOL-NOT-EUR-PREFIX",
	// The credit register (#3768, #3895). ONE ROW PER WAY OF GETTING IT WRONG, and every one of
	// those mistakes renders the REST of the block correctly, which is what makes each row
	// load-bearing rather than decorative: dropping the sign, signing the zero, rounding half to
	// EVEN — this package's founding defect, met again at a register that rounds to whole units —
	// deciding the sign on the raw amount rather than on the rendered magnitude, which resurrects
	// `+$0/mo` for a change too small to show, rounding the decimal a human typed rather than the
	// binary product the scale produces, and pre-rounding at a fixed two places rather than at the
	// places being printed.
	//
	// NO COUNT IN THAT SENTENCE, deliberately. It read "Four separate mistakes ... so all four are
	// named" over five ids, and had been wrong since the fifth was added: a hand-typed number in a
	// comment beside a list is a second source of truth for the list's length and decays the first
	// time the list grows. The identical sentence carried the identical error in
	// packages/format/tests/conformance.test.ts.
	"monthlyDelta/estimate/A-SAVING-KEEPS-ITS-SIGN",
	"monthlyDelta/estimate/AN-INCREASE-IS-SIGNED-TOO",
	"monthlyDelta/exact/ZERO-CARRIES-NO-SIGN-AND-NO-MINOR-UNITS",
	"monthlyDelta/exact/JPY-HALF-ROUNDS-AWAY-FROM-ZERO",
	"monthlyDelta/estimate/A-SUB-UNIT-INCREASE-ROUNDS-TO-NO-CHANGE",
	// #3895. Three decimals, so `roundHalfAwayFromZero`'s multiply lands on the far side of a half
	// from the literal — `8.165 * 100` is 816.4999999999999. Every other row in this section stays
	// inside two decimals, where the binary product is exact and the two languages cannot disagree,
	// so the section looked like it pinned the rounding rule and pinned a different one.
	"monthlyDelta/exact/BINARY-SCALE-8.165-ROUNDS-DOWN",
	"monthlyDelta/exact/BINARY-SCALE-8.165-ROUNDS-DOWN-A-SAVING-TOO",
	"monthlyDelta/exact/BINARY-SCALE-1.005-ROUNDS-DOWN",
	"monthlyDelta/exact/BINARY-SCALE-1.005-ROUNDS-DOWN-A-SAVING-TOO",
	// ...and the rows that hold the OTHER side to `render`'s "round once, at the places you print"
	// rule. A TypeScript pre-round hardcoded to two places double-rounds 12.496 up to 13 in every
	// zero-decimal register, against Go's 12.
	"monthlyDelta/estimate/DOUBLE-ROUNDING-12.496-IS-NOT-A-HALF",
	"monthlyDelta/exact/DOUBLE-ROUNDING-12.496-IS-NOT-A-HALF-AT-JPY",
	// MonthlyRate clamps a negative, and that is a REFUSAL rather than a gap now that MonthlyDelta
	// exists. These two rows are the only statement that the clamp is deliberate; without them a
	// later reader "fixes" it and every absolute call site starts rendering signed money.
	"monthlyRate/estimate/negative-REFUSED-see-monthlyDelta",
	"monthlyRate/exact/negative-REFUSED-see-monthlyDelta",
	// #3899, and the same argument one register over. `money` had NO pre-round and
	// `formatMonthlyRate` had one hardcoded to two places, so the four `money` rows below diverged
	// outright and the three JPY rows double-rounded. Every other row in both sections lives inside
	// two decimals and a two-decimal currency, where the two implementations cannot disagree — so
	// both sections looked like they pinned the rounding rule and pinned a weaker one.
	"money/THREE-DECIMAL-CENTS-ROUND-AWAY-FROM-ZERO",
	"money/three-decimal-cents-at-one-unit",
	"money/negative-three-decimal-cents",
	// `EUR` as well as `USD`, because the divergence is in the shared rounding step and a reader
	// should not be able to conclude it was ever about the symbol table.
	"money/three-decimal-cents-EUR",
	// The SIGN axis, and the reason it is here rather than in the section it passes in: JS
	// `Math.round` is half-UP and Go's `math.Round` is half-AWAY-FROM-ZERO, so they disagree on
	// every negative half. This row PASSED before #3899 and must keep passing — it is what fails
	// the plausible one-line fix that rounds the signed value instead of the magnitude.
	"money/NEGATIVE-HALF-CENT-ROUNDS-AWAY-FROM-ZERO-NOT-TOWARD-POSITIVE",
	// The TIE axis. `2.675 * 100` is EXACTLY `267.5`, so this row agrees only because both
	// languages take a tie away from zero; it reds a fix that reaches for Go-native half-to-even.
	// A different mechanism from the four above, which is why it is named rather than counted.
	"money/three-decimal-cents-that-agreed-all-along",
	// ── #3581, THE DIVISOR AXIS ─────────────────────────────────────────────────────────────────
	// `formatMoney` divided by 100 unconditionally, so every zero-decimal currency rendered at 1/100
	// of its value. These rows exist because BOTH ways of being wrong render the rest of this
	// section correctly, and because the second way is the one a reader reaches for first.
	//
	// Dividing everything by 100 reds the JPY, KRW and CLP rows. Taking the exponent from CLDR
	// instead — the plausible fix — reds ISK, UGX and TWD, whose CHARGE divisor is 100 while CLDR
	// prints 0, 0 and 2 fraction digits. UGX is the sharpest of the set: it is IN Stripe's published
	// zero-decimal list AND in that page's Special cases table saying to send two-decimal amounts,
	// so a table transcribed from the list alone renders it 100x overstated and passes everything
	// else here. CLP and TWD share the narrow symbol `$` and not a divisor, which is what stops the
	// divisor being read as a property of the symbol.
	//
	// HUF is the fourth currency the divisor table names and is deliberately NOT pinned: its CLDR
	// display digits moved 2 -> 0 between ICU 75.1 and ICU 78.3, so a row for it would change under
	// a Node upgrade nobody made. Its divisor is pinned in the TypeScript unit tests instead.
	"money/JPY-HAS-NO-MINOR-UNIT-SO-IT-IS-NOT-DIVIDED",
	"money/KRW-IS-ZERO-DECIMAL-TOO-NOT-JUST-JPY",
	"money/ISK-IS-CLDR-ZERO-DECIMAL-AND-STRIPE-TWO-DECIMAL",
	"money/UGX-IS-IN-STRIPES-ZERO-DECIMAL-LIST-AND-IS-STILL-DIVIDED",
	"money/CLP-AND-TWD-SHARE-A-SYMBOL-AND-NOT-A-DIVISOR",
	"money/TWD-shares-CLPs-symbol-and-is-divided",
	// The sign at a tie the two-decimal rows cannot reach: with the divisor at 1 the rounding step
	// runs at 0 places, so `-1234.5` IS the half. JS `Math.round` is half-UP and Go `math.Round` is
	// half-away-from-zero, so a fix that rounds the signed value renders `-¥1,234` here.
	"money/JPY-NEGATIVE-HALF-UNIT-ROUNDS-AWAY-FROM-ZERO-NOT-TOWARD-POSITIVE",
	// The `<1` test is asked AFTER the single rounding, at the currency's OWN places. The last of
	// these is the worst failure in the set: at a fixed two places, `0.6` JPY renders `<¥1/mo` —
	// the register ADMITTING it does not know, about a value that rounds cleanly to one whole unit.
	"monthlyRate/estimate/JPY-ROUNDS-ONCE-AT-ZERO-PLACES",
	"monthlyRate/exact/JPY-ROUNDS-ONCE-AT-ZERO-PLACES",
	"monthlyRate/estimate/JPY-SUB-UNIT-THAT-ROUNDS-UP-IS-NOT-LESS-THAN-ONE",
	// And the USD three-decimal rows, which did NOT diverge — `formatMonthlyRate` already
	// pre-rounded. They are required anyway: delete them and the pre-round can go back to being
	// absent with every layer green, which is the state #3899 measured.
	"monthlyRate/exact/THREE-DECIMAL-ROUNDS-AWAY-FROM-ZERO",
	"monthlyRate/estimate/three-decimal-rounds-away-from-zero",
	"monthlyRate/exact/three-decimal-at-one-unit",
}

// tableProblems IS the guard. Both the check above and the mutation test that proves it works call
// this one function.
//
// That is not a stylistic preference. The first cut of this pattern elsewhere in the repo
// re-implemented the maps and the loops inline in the mutation test, so it verified a COPY of the
// guard and would have passed against a revert to the inert count-threshold form. A test that
// re-implements what it is testing tests nothing about the thing.
//
// Returns one message per unsatisfied requirement; empty means the table still carries what this
// mirror exists to lock.
func tableProblems(tbl tableFile) []string {
	var problems []string

	if len(tbl.Cases) == 0 {
		return []string{fmt.Sprintf("%s parsed to zero sections — every assertion below is unreachable and this test would pass vacuously.\n%s", tableRel, regenerate)}
	}

	// Every section must be driven or declared excluded. A section with neither is a silent gap —
	// the TypeScript generator already refuses one, and Go refusing it too is what keeps the two
	// halves the same shape.
	for section, rows := range tbl.Cases {
		if len(rows) == 0 {
			problems = append(problems, fmt.Sprintf("section %q carries zero rows — 'ran nothing' must not read as 'nothing wrong'", section))
		}
		if _, driven := drivers[section]; !driven {
			problems = append(problems, fmt.Sprintf(
				"section %q has no Go driver. Either implement it and add a line to `drivers`, or — if Go "+
					"deliberately does not mirror it — the TypeScript side must move it to `excluded` with a "+
					"stated reason. A section Go quietly skips is the gap this file exists to close.", section))
		}
	}
	for section := range drivers {
		if _, present := tbl.Cases[section]; !present {
			problems = append(problems, fmt.Sprintf(
				"Go drives section %q but the table has no such section — the driver asserts nothing", section))
		}
	}

	// The one declared exclusion, asserted rather than assumed. If TypeScript ever ports Relative,
	// this fires and Go is told to mirror it instead of silently continuing not to.
	if _, ok := tbl.Excluded["formatRelative"]; !ok {
		problems = append(problems, "the table no longer excludes formatRelative — Go must either mirror it or the exclusion must be restored with its reason")
	}
	for name, reason := range tbl.Excluded {
		if len(strings.TrimSpace(reason)) < 40 {
			problems = append(problems, fmt.Sprintf("exclusion %q has no real reason (%q) — an absence with a stated reason is reviewable, %q is not", name, reason, "n/a"))
		}
	}

	// ── #4123. THE SET, NOT THE ROWS ───────────────────────────────────────────────────────────
	//
	// `stripeZeroDecimalCharge` in format.go and `STRIPE_ZERO_DECIMAL_CHARGE` in
	// packages/format/src/minor-units.ts are the same fifteen codes, and until this check nothing
	// held them together. The rows above pin how six currencies RENDER, and a row can only pin a
	// code it NAMES — so a sixteenth code added to one language moved no expectation in this file,
	// and format_test.go's own hand-typed list only ever caught a REMOVAL from the map beside it.
	// Adding a row per currency would have pinned fifteen and left the identical hole at sixteen.
	// The axis the two implementations differ on is set MEMBERSHIP, so membership is what crosses.
	//
	// The expected value comes from the ARTIFACT and from nowhere else. A second list typed here
	// would be a copy of what it is checking: it would agree with Go's map because the same hand
	// wrote both, and a TypeScript-only addition would still land green.
	problems = append(problems, zeroDecimalProblems(tbl)...)

	// Named rows, present AND still carrying their recorded answer. Presence alone is not enough: a
	// row retained but regenerated to a different expectation proves nothing about the boundary it
	// was written for.
	seen := map[string]bool{}
	for _, rows := range tbl.Cases {
		for _, row := range rows {
			if id, ok := row["id"].(string); ok {
				if want, ok := row["want"].(string); ok && want != "" {
					seen[id] = true
				}
			}
		}
	}
	for _, id := range requiredIDs {
		if !seen[id] {
			problems = append(problems, fmt.Sprintf(
				"row %q is missing from the table, or no longer carries an expectation — it is one of the "+
					"rows this mirror exists to lock. If it is genuinely obsolete, delete it from requiredIDs "+
					"in the same commit and say why in the PR.", id))
		}
	}
	return problems
}

// zeroDecimalProblems holds `stripeZeroDecimalCharge` to the set TypeScript published (#4123).
//
// Four refusals precede the comparison, and each one exists because its absence would read as
// agreement rather than as a failure to measure:
//
//   - VERSION. A table written before the key existed decodes `ZeroDecimalCharge` as nil, which is
//     indistinguishable at this point from TypeScript deliberately emptying the set. The version
//     floor separates them, and it is why the generator bumped VERSION to 2 rather than quietly
//     adding a key.
//   - EMPTY. `nil` compared against a map of fifteen would fire fifteen "TypeScript has no such
//     code" messages naming everything except the actual problem, so say the actual problem.
//   - GO'S OWN MAP EMPTY. The inverse, and it is not hypothetical in the way it sounds: `Money`
//     would then divide every currency by 100 — the exact defect #3581 was — and a comparison
//     against an equally empty published list would call it conformant.
//   - NOT UPPER CASE (#4174). A malformed artifact, refused before the diff runs rather than
//     repaired into one. See below; this is the refusal that replaced a `strings.ToUpper`.
//
// ── WHY THIS SIDE NO LONGER NORMALISES (#4174) ──────────────────────────────────────────────
//
// This function used to index the artifact as `published[strings.ToUpper(code)]`. TypeScript
// normalises only the QUERY — `ZERO_DECIMAL_CHARGE.has(currency.toUpperCase())` — so a lowercase
// entry is INERT there while Go read it as an upper-case code TypeScript had declared. The two
// sides disagreed about what the artifact MEANS, and the disagreement was invisible because every
// layer passed it: the generator's sortedness refusal (a lowercase code sorts after `XPF`), the
// `not.toContain("UGX")` assertions (`===`, so no match), and the equality assertion (the same
// literal on both sides). What fired instead was the `missing` branch below, saying "TypeScript
// treats UGX as zero-decimal … Add them there" — FALSE, and a reader who followed it added UGX to
// `stripeZeroDecimalCharge` and got the 100x-overstated invoice #4101 exists to prevent, with this
// guard then green. Measured on 09b01b60 with `kwd`: the whole Go suite passed afterwards, and
// `Money(500, "KWD")` answered "500.00 KWD" against TypeScript's "KWD 5.000".
//
// So it is refused rather than normalised, and DELETING the ToUpper alone would not have been
// enough: a lowercase code would still have reached the diff and still produced that same
// sentence, one case-fold different. A consumer that repairs its input cannot report on it.
// The producer refuses it too (`zeroDecimalCharge()` in gen-format-conformance.ts) — this is the
// half that also covers an artifact already carrying one, which the producer's refusal cannot.
//
// Order-insensitive: both sides are sorted before the diff. Sortedness of the ARTIFACT is asserted
// on the TypeScript side, where it is a claim about the file that side writes.
func zeroDecimalProblems(tbl tableFile) []string {
	if tbl.Version < schemaVersion {
		return []string{fmt.Sprintf(
			"%s is at schema version %d; this mirror needs %d, the shape that carries `zeroDecimalCharge`. "+
				"Below that the key is absent and its absence is indistinguishable from an empty set.\n%s",
			tableRel, tbl.Version, schemaVersion, regenerate)}
	}
	if len(tbl.ZeroDecimalCharge) == 0 {
		return []string{fmt.Sprintf(
			"%s carries no `zeroDecimalCharge` codes. Go's own set has %d, and 'nothing to compare' must "+
				"not exit like 'nothing wrong'.\n%s", tableRel, len(stripeZeroDecimalCharge), regenerate)}
	}
	if len(stripeZeroDecimalCharge) == 0 {
		return []string{"stripeZeroDecimalCharge is empty — Money would divide every currency by 100, which is #3581. " +
			"An empty set cannot be held to a published list; it agrees with nothing."}
	}

	var notUpper []string
	published := map[string]bool{}
	for _, code := range tbl.ZeroDecimalCharge {
		if code != strings.ToUpper(code) {
			notUpper = append(notUpper, code)
			continue
		}
		published[code] = true
	}
	// Returned rather than accumulated, so the diff below never runs on an artifact this side
	// cannot read. Falling through would compare a set with a hole in it and report the hole as a
	// Go-only code — a second false message, arrived at from the same normalising instinct.
	if len(notUpper) > 0 {
		sort.Strings(notUpper)
		return []string{fmt.Sprintf(
			"%s publishes %s in `zeroDecimalCharge`, which is not upper case. This is a MALFORMED ARTIFACT, "+
				"not a code TypeScript declared: `stripeChargeDivisor` uppercases the query and never the "+
				"entries, so TypeScript's own set does not contain it either and `stripeChargeDivisor` still "+
				"answers 100 for it. Do NOT add it to `stripeZeroDecimalCharge` — for UGX that is precisely the "+
				"100x-overstated invoice #4101 exists to prevent. Fix the case in STRIPE_ZERO_DECIMAL_CHARGE in "+
				"packages/format/src/minor-units.ts and regenerate.\n%s",
			tableRel, strings.Join(notUpper, ", "), regenerate)}
	}

	var problems []string
	var missing, extra []string
	for code := range published {
		if !stripeZeroDecimalCharge[code] {
			missing = append(missing, code)
		}
	}
	for code := range stripeZeroDecimalCharge {
		if !published[code] {
			extra = append(extra, code)
		}
	}
	sort.Strings(missing)
	sort.Strings(extra)

	if len(missing) > 0 {
		problems = append(problems, fmt.Sprintf(
			"TypeScript treats %s as zero-decimal for CHARGES and `stripeZeroDecimalCharge` in format.go does not. "+
				"Add them there — an amount in one of these renders 100x too SMALL in Go. Do NOT regenerate the "+
				"table to make this pass: the table is TypeScript's statement, not Go's.",
			strings.Join(missing, ", ")))
	}
	if len(extra) > 0 {
		problems = append(problems, fmt.Sprintf(
			"`stripeZeroDecimalCharge` in format.go treats %s as zero-decimal for CHARGES and TypeScript does not. "+
				"Either remove them there, or — if Stripe really publishes them for charges — add them to "+
				"STRIPE_ZERO_DECIMAL_CHARGE in packages/format/src/minor-units.ts and regenerate. An amount in one "+
				"of these renders 100x too LARGE in Go, which reads as a plausible bill. UGX is the code to check "+
				"first: it is IN Stripe's published list and excluded here on purpose.",
			strings.Join(extra, ", ")))
	}
	return problems
}

// The guard is only worth having if it FAILS on the mutations it describes, so this drives them
// through tableProblems itself rather than asserting them in a comment.
func TestTableGuardFailsOnEachMutation(t *testing.T) {
	base := loadTable(t)
	if got := tableProblems(base); len(got) != 0 {
		t.Fatalf("the unmutated table already fails the guard, so this test cannot prove anything: %v", got)
	}

	t.Run("a removed required row is detected", func(t *testing.T) {
		victim := requiredIDs[0]
		mutated := cloneWithout(base, victim)
		problems := tableProblems(mutated)
		if len(problems) != 1 {
			t.Fatalf("removing %q should leave exactly 1 problem, got %d: %v", victim, len(problems), problems)
		}
		if !strings.Contains(problems[0], victim) {
			t.Errorf("the guard fired but did not name the row that was removed: %q", problems[0])
		}
	})

	t.Run("an undriven section is detected", func(t *testing.T) {
		mutated := clone(base)
		mutated.Cases["percent"] = []map[string]any{{"id": "percent/x", "want": "1%"}}
		problems := tableProblems(mutated)
		if len(problems) != 1 || !strings.Contains(problems[0], "percent") {
			t.Fatalf("a new section with no Go driver must be reported, got %v", problems)
		}
	})

	t.Run("a dropped exclusion is detected", func(t *testing.T) {
		mutated := clone(base)
		delete(mutated.Excluded, "formatRelative")
		problems := tableProblems(mutated)
		if len(problems) != 1 || !strings.Contains(problems[0], "formatRelative") {
			t.Fatalf("dropping the declared exclusion must be reported, got %v", problems)
		}
	})

	// ── #4123. The mutation this whole change exists for: a code added to ONE language.
	//
	// Driven in BOTH directions, because they fail for different reasons and only one of them is
	// the one a reader expects. A TypeScript-only addition arrives here as a code the artifact
	// carries and Go's map does not; a Go-only addition arrives as its mirror image, and that is
	// the direction no layer could see before — the conformance rows pin only the codes they name,
	// and format_test.go's hand-typed list only catches a removal.
	t.Run("a code TypeScript added and Go did not is detected", func(t *testing.T) {
		mutated := clone(base)
		mutated.ZeroDecimalCharge = append(mutated.ZeroDecimalCharge, "ZWG")
		problems := zeroDecimalProblems(mutated)
		if len(problems) != 1 || !strings.Contains(problems[0], "ZWG") {
			t.Fatalf("a published code missing from stripeZeroDecimalCharge must be reported by name, got %v", problems)
		}
		// And through the real guard, not only the helper — the check must actually be WIRED.
		if wired := tableProblems(mutated); len(wired) != 1 || !strings.Contains(wired[0], "ZWG") {
			t.Fatalf("tableProblems does not carry the zero-decimal check, got %v", wired)
		}
	})

	t.Run("a code Go added and TypeScript did not is detected", func(t *testing.T) {
		mutated := clone(base)
		// Dropping a code from the PUBLISHED list is the same shape as adding it to Go's map:
		// either way Go's set is the larger one. Mutating the artifact rather than the package-level
		// map keeps the subtests independent of each other's ordering.
		victim := mutated.ZeroDecimalCharge[0]
		mutated.ZeroDecimalCharge = append([]string(nil), mutated.ZeroDecimalCharge[1:]...)
		problems := zeroDecimalProblems(mutated)
		if len(problems) != 1 || !strings.Contains(problems[0], victim) {
			t.Fatalf("a Go-only code must be reported by name, got %v", problems)
		}
	})

	// ── #4174. The mutation the guard used to answer FALSELY.
	//
	// Not "does it fail" — it always failed. What is asserted is WHICH failure, because the one it
	// used to give named a fix that causes the defect. The negative assertion quotes the OLD
	// message, so it is hand-authored from the guard as it stood at 09b01b60 rather than built out
	// of the refusal being added; if somebody restores the normalising read, this subtest is what
	// goes red, and it goes red on the sentence rather than on the exit code.
	t.Run("a lowercase published code is refused, not read as a TypeScript declaration", func(t *testing.T) {
		mutated := clone(base)
		mutated.ZeroDecimalCharge = append(mutated.ZeroDecimalCharge, "ugx")
		problems := zeroDecimalProblems(mutated)
		if len(problems) != 1 {
			t.Fatalf("a lowercase published code must be reported as exactly 1 problem, got %d: %v", len(problems), problems)
		}
		if !strings.Contains(problems[0], "ugx") {
			t.Errorf("the refusal must name the code AS PUBLISHED, so the reader can find it: %q", problems[0])
		}
		// The whole point. This is the sentence the guard used to emit, and following it is what
		// produced the 100x-overstated UGX invoice.
		if strings.Contains(problems[0], "Add them there") {
			t.Errorf("the guard is still prescribing the defect — a lowercase entry is INERT in TypeScript, "+
				"so telling the reader to add it to stripeZeroDecimalCharge is false: %q", problems[0])
		}
		if strings.Contains(problems[0], "TypeScript treats") {
			t.Errorf("a lowercase entry is not something TypeScript treats as anything: %q", problems[0])
		}
		// And through the real guard, not only the helper — the refusal must actually be WIRED.
		if wired := tableProblems(mutated); len(wired) != 1 || !strings.Contains(wired[0], "ugx") {
			t.Fatalf("tableProblems does not carry the case refusal, got %v", wired)
		}
	})

	// The refusal must not be satisfiable by dropping the offending code and diffing the rest: that
	// would compare a set with a hole in it and report the hole as a Go-only code, which is the same
	// false-message shape one step along. A lowercase spelling of a code Go's map DOES hold is the
	// case that separates the two — `published` would be short one entry either way.
	t.Run("a lowercase spelling of a code Go holds is still refused for its CASE", func(t *testing.T) {
		mutated := clone(base)
		victim := mutated.ZeroDecimalCharge[0]
		mutated.ZeroDecimalCharge[0] = strings.ToLower(victim)
		problems := zeroDecimalProblems(mutated)
		if len(problems) != 1 || !strings.Contains(problems[0], strings.ToLower(victim)) {
			t.Fatalf("a lowercased %s must be refused as malformed, got %v", victim, problems)
		}
		if strings.Contains(problems[0], "treats "+victim) {
			t.Errorf("%s was reported as a Go-only code rather than as a case problem: %q", victim, problems[0])
		}
	})

	t.Run("an absent or empty zero-decimal set is detected", func(t *testing.T) {
		mutated := clone(base)
		mutated.ZeroDecimalCharge = nil
		problems := zeroDecimalProblems(mutated)
		if len(problems) != 1 || !strings.Contains(problems[0], "zeroDecimalCharge") {
			t.Fatalf("an empty published set must be reported as such, not as fifteen missing codes, got %v", problems)
		}
	})

	t.Run("a table below the schema version is detected", func(t *testing.T) {
		mutated := clone(base)
		mutated.Version = schemaVersion - 1
		mutated.ZeroDecimalCharge = nil // what an older generator would have produced
		problems := zeroDecimalProblems(mutated)
		if len(problems) != 1 || !strings.Contains(problems[0], "schema version") {
			t.Fatalf("a pre-v2 table must be refused for its SHAPE, not read as an empty set, got %v", problems)
		}
	})

	t.Run("an empty table is detected", func(t *testing.T) {
		problems := tableProblems(tableFile{Cases: map[string][]map[string]any{}})
		if len(problems) != 1 || !strings.Contains(problems[0], "vacuously") {
			t.Fatalf("a table with no sections must be reported as vacuous, got %v", problems)
		}
	})
}

func clone(in tableFile) tableFile {
	out := tableFile{
		Version:  in.Version,
		Excluded: map[string]string{},
		// Copied, not shared: the mutations below append to it, and `append` on a shared backing
		// array can write THROUGH into the base table and make a later subtest measure a mutated
		// input while reporting on the original.
		ZeroDecimalCharge: append([]string(nil), in.ZeroDecimalCharge...),
		Cases:             map[string][]map[string]any{},
	}
	for k, v := range in.Excluded {
		out.Excluded[k] = v
	}
	for section, rows := range in.Cases {
		out.Cases[section] = append([]map[string]any(nil), rows...)
	}
	return out
}

func cloneWithout(in tableFile, id string) tableFile {
	out := clone(in)
	for section, rows := range out.Cases {
		kept := make([]map[string]any, 0, len(rows))
		for _, r := range rows {
			if r["id"] != id {
				kept = append(kept, r)
			}
		}
		out.Cases[section] = kept
	}
	return out
}
