// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by apps/console/scripts/gen-go-brand.ts; DO NOT EDIT.
// Regenerate with: pnpm -C apps/console run gen:go-brand
//
// Source of truth: packages/brand/src/tokens.css (the values) and apps/console/scripts/lib/brand-projection.ts (the decisions).
//
// Every custom property declared in the stylesheet appears in BrandProjections below with
// exactly one of exact / lossy / none. 65 exact, 19 lossy, 86 none — 170 tokens, no gaps.
// The generator refuses to emit if a declared token has no decision, so a token added to the
// console fails CI until somebody says what the CLI does with it. A "none" entry is a real
// answer, not an omission: a spinner has no easing curve and a CLI cannot set a font.
//
// The lossy entries carry their reason INTO this file on purpose. --radius-sm and --radius-md
// render as the same border here; a reader who does not find the sentence saying so will file
// it as a bug and "fix" it.

package types

import "time"

// BrandProjectionKind is how faithfully a brand token survives the trip to a terminal.
type BrandProjectionKind string

const (
	// BrandExact — the terminal carries the token's value or its ordering without loss.
	BrandExact BrandProjectionKind = "exact"
	// BrandLossy — the terminal carries the INTENT; Note says what it collapses to and why.
	BrandLossy BrandProjectionKind = "lossy"
	// BrandNone — no terminal analogue; Note is the one-line reason.
	BrandNone BrandProjectionKind = "none"
)

// BrandProjection is one token's decision. Target names the Go identifier holding the value,
// and is empty exactly when Kind is BrandNone.
type BrandProjection struct {
	Token  string
	Kind   BrandProjectionKind
	Target string
	Note   string
}

// BrandProjections is every token declared in packages/brand/src/tokens.css, in stylesheet order.
var BrandProjections = []BrandProjection{
	{Token: "--color-background", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --background — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --background."},
	{Token: "--color-foreground", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --foreground — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --foreground."},
	{Token: "--font-sans", Kind: BrandNone, Target: "", Note: "the CLI cannot set a font. The typeface is the terminal emulator's, chosen by the person running it, and no escape sequence changes it."},
	{Token: "--font-mono", Kind: BrandNone, Target: "", Note: "the CLI cannot set a font — and a terminal is already monospaced, so the one thing this token buys the console it gets for free."},
	{Token: "--font-display", Kind: BrandNone, Target: "", Note: "the CLI cannot set a font. The display voice projects as EmphasisDisplay (weight and case), not as a face."},
	{Token: "--font-grotesk", Kind: BrandNone, Target: "", Note: "the CLI cannot set a font. Space Grotesk is the display lockup's face; in the terminal the lockup is the [·] mark and the eyebrow device."},
	{Token: "--color-sidebar-ring", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --sidebar-ring — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --sidebar-ring projects to nothing either; its own entry says why."},
	{Token: "--color-sidebar-border", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --sidebar-border — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --sidebar-border projects to nothing either; its own entry says why."},
	{Token: "--color-sidebar-accent-foreground", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --sidebar-accent-foreground — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --sidebar-accent-foreground projects to nothing either; its own entry says why."},
	{Token: "--color-sidebar-accent", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --sidebar-accent — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --sidebar-accent projects to nothing either; its own entry says why."},
	{Token: "--color-sidebar-primary-foreground", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --sidebar-primary-foreground — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --sidebar-primary-foreground projects to nothing either; its own entry says why."},
	{Token: "--color-sidebar-primary", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --sidebar-primary — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --sidebar-primary projects to nothing either; its own entry says why."},
	{Token: "--color-sidebar-foreground", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --sidebar-foreground — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --sidebar-foreground projects to nothing either; its own entry says why."},
	{Token: "--color-sidebar", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --sidebar — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --sidebar projects to nothing either; its own entry says why."},
	{Token: "--color-chart-5", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --chart-5 — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --chart-5 projects to nothing either; its own entry says why."},
	{Token: "--color-chart-4", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --chart-4 — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --chart-4 projects to nothing either; its own entry says why."},
	{Token: "--color-chart-3", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --chart-3 — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --chart-3 projects to nothing either; its own entry says why."},
	{Token: "--color-chart-2", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --chart-2 — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --chart-2 projects to nothing either; its own entry says why."},
	{Token: "--color-chart-1", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --chart-1 — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --chart-1 projects to nothing either; its own entry says why."},
	{Token: "--color-ring", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --ring — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --ring is projected on the focus port, not as a colour."},
	{Token: "--color-input", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --input — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --input."},
	{Token: "--color-border", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --border — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --border."},
	{Token: "--color-destructive", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --destructive — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --destructive."},
	{Token: "--color-accent-foreground", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --accent-foreground — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --accent-foreground."},
	{Token: "--color-accent", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --accent — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --accent."},
	{Token: "--color-muted-foreground", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --muted-foreground — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --muted-foreground."},
	{Token: "--color-muted", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --muted — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --muted."},
	{Token: "--color-secondary-foreground", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --secondary-foreground — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --secondary-foreground."},
	{Token: "--color-secondary", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --secondary — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --secondary."},
	{Token: "--color-primary-foreground", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --primary-foreground — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --primary-foreground."},
	{Token: "--color-primary", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --primary — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --primary."},
	{Token: "--color-popover-foreground", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --popover-foreground — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --popover-foreground."},
	{Token: "--color-popover", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --popover — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --popover."},
	{Token: "--color-card-foreground", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --card-foreground — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --card-foreground."},
	{Token: "--color-card", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --card — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --card."},
	{Token: "--color-surface", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --surface — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --surface."},
	{Token: "--color-surface-raised", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --surface-raised — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --surface-raised."},
	{Token: "--color-surface-sunken", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --surface-sunken — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --surface-sunken."},
	{Token: "--color-surface-muted", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --surface-muted — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --surface-muted."},
	{Token: "--color-text-primary", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --text-primary — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --text-primary."},
	{Token: "--color-text-secondary", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --text-secondary — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --text-secondary."},
	{Token: "--color-text-tertiary", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --text-tertiary — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --text-tertiary."},
	{Token: "--color-text-disabled", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --text-disabled — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --text-disabled."},
	{Token: "--color-ink", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --ink — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --ink."},
	{Token: "--color-ink-hover", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --ink-hover — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --ink-hover."},
	{Token: "--color-ink-foreground", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --ink-foreground — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --ink-foreground."},
	{Token: "--color-border-strong", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --border-strong — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --border-strong."},
	{Token: "--color-border-faint", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --border-faint — it exists so `bg-…`/`text-…` compile, and holds no value of its own. The colour is projected at --border-faint."},
	{Token: "--color-overlay", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --overlay — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --overlay projects to nothing either; its own entry says why."},
	{Token: "--color-input-fill", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --input-fill — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --input-fill projects to nothing either; its own entry says why."},
	{Token: "--color-input-fill-hover", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --input-fill-hover — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --input-fill-hover projects to nothing either; its own entry says why."},
	{Token: "--color-ring-invalid", Kind: BrandNone, Target: "", Note: "Tailwind `@theme inline` utility binding for --ring-invalid — it exists so `bg-…`/`text-…` compile, and holds no value of its own. --ring-invalid is projected on the focus port, not as a colour."},
	{Token: "--radius-xs", Kind: BrandLossy, Target: "BorderSquare", Note: "0 — no corner at all."},
	{Token: "--radius-sm", Kind: BrandLossy, Target: "BorderSquare", Note: "2px. A cell has no sub-pixel: below one cell's worth of corner there is nothing the terminal can draw but a square angle. DELIBERATELY the same border as --radius-md — that is not a bug to fix."},
	{Token: "--radius-md", Kind: BrandLossy, Target: "BorderSquare", Note: "3px. Same collapse as --radius-sm, and deliberately identical to it."},
	{Token: "--radius-lg", Kind: BrandLossy, Target: "BorderRounded", Note: "4px. From here up the console's corner is legible, so the terminal spends its one rounded border set (╭╮╰╯) on it. DELIBERATELY the same border as --radius-xl and --radius."},
	{Token: "--radius-xl", Kind: BrandLossy, Target: "BorderRounded", Note: "6px. Same collapse as --radius-lg, and deliberately identical to it."},
	{Token: "--radius", Kind: BrandLossy, Target: "BorderRounded", Note: "0.25rem — the shadcn base radius, 4px at the default root size. Same collapse as --radius-lg."},
	{Token: "--gray-0", Kind: BrandExact, Target: "ColorGray0", Note: "ink ramp step"},
	{Token: "--gray-25", Kind: BrandExact, Target: "ColorGray25", Note: "ink ramp step"},
	{Token: "--gray-50", Kind: BrandExact, Target: "ColorGray50", Note: "ink ramp step"},
	{Token: "--gray-100", Kind: BrandExact, Target: "ColorGray100", Note: "ink ramp step"},
	{Token: "--gray-200", Kind: BrandExact, Target: "ColorGray200", Note: "ink ramp step"},
	{Token: "--gray-300", Kind: BrandExact, Target: "ColorGray300", Note: "ink ramp step"},
	{Token: "--gray-400", Kind: BrandExact, Target: "ColorGray400", Note: "ink ramp step"},
	{Token: "--gray-500", Kind: BrandExact, Target: "ColorGray500", Note: "ink ramp step"},
	{Token: "--gray-550", Kind: BrandExact, Target: "ColorGray550", Note: "ink ramp step"},
	{Token: "--gray-600", Kind: BrandExact, Target: "ColorGray600", Note: "ink ramp step"},
	{Token: "--gray-625", Kind: BrandExact, Target: "ColorGray625", Note: "ink ramp step"},
	{Token: "--gray-700", Kind: BrandExact, Target: "ColorGray700", Note: "ink ramp step"},
	{Token: "--gray-800", Kind: BrandExact, Target: "ColorGray800", Note: "ink ramp step"},
	{Token: "--gray-900", Kind: BrandExact, Target: "ColorGray900", Note: "ink ramp step"},
	{Token: "--gray-950", Kind: BrandExact, Target: "ColorGray950", Note: "ink ramp step"},
	{Token: "--gray-1000", Kind: BrandExact, Target: "ColorGray1000", Note: "ink ramp step"},
	{Token: "--gray-1050", Kind: BrandExact, Target: "ColorGray1050", Note: "ink ramp step"},
	{Token: "--gray-1100", Kind: BrandExact, Target: "ColorGray1100", Note: "ink ramp step"},
	{Token: "--black", Kind: BrandExact, Target: "ColorBlack", Note: "the brand black — app icons, OG images, the PWA manifest"},
	{Token: "--surface", Kind: BrandExact, Target: "ColorSurface", Note: "the plate a panel is drawn on"},
	{Token: "--surface-raised", Kind: BrandExact, Target: "ColorSurfaceRaised", Note: "a panel lifted off the plate"},
	{Token: "--surface-sunken", Kind: BrandExact, Target: "ColorSurfaceSunken", Note: "a well — a scroll region, a code block"},
	{Token: "--surface-muted", Kind: BrandExact, Target: "ColorSurfaceMuted", Note: "a quiet fill — a selected row, an inactive tab"},
	{Token: "--text-primary", Kind: BrandExact, Target: "ColorTextPrimary", Note: "headings, values, emphasis — the CLI's InkPrimary"},
	{Token: "--text-secondary", Kind: BrandExact, Target: "ColorTextSecondary", Note: "body text — the CLI's InkSecondary"},
	{Token: "--text-tertiary", Kind: BrandExact, Target: "ColorTextTertiary", Note: "labels and rules — the CLI's InkMuted"},
	{Token: "--text-disabled", Kind: BrandExact, Target: "ColorTextDisabled", Note: "the dimmest readable ink — the CLI's InkFaint"},
	{Token: "--text-on-ink", Kind: BrandExact, Target: "ColorTextOnInk", Note: "foreground on an inverted (ink) surface — the CLI's InkInverse"},
	{Token: "--border-strong", Kind: BrandLossy, Target: "ColorBorderStrong", Note: "carries alpha in one theme; a terminal cell has no alpha channel, so the value is flattened against --background for that theme. Over a raised surface the browser resolves it lighter than this."},
	{Token: "--border-faint", Kind: BrandLossy, Target: "ColorBorderFaint", Note: "carries alpha in one theme; a terminal cell has no alpha channel, so the value is flattened against --background for that theme. Over a raised surface the browser resolves it lighter than this."},
	{Token: "--ink", Kind: BrandExact, Target: "ColorInk", Note: "the solid emphasis fill"},
	{Token: "--ink-hover", Kind: BrandExact, Target: "ColorInkHover", Note: "its hover step; the CLI reuses it for a focused row's fill"},
	{Token: "--ink-foreground", Kind: BrandExact, Target: "ColorInkForeground", Note: "foreground on the ink fill"},
	{Token: "--signal-strong", Kind: BrandExact, Target: "ColorSignalStrong", Note: "an active/online subject"},
	{Token: "--signal-mute", Kind: BrandExact, Target: "ColorSignalMute", Note: "a pending subject"},
	{Token: "--signal-faint", Kind: BrandExact, Target: "ColorSignalFaint", Note: "a disabled subject"},
	{Token: "--signal-critical", Kind: BrandExact, Target: "ColorSignalCritical", Note: "a failed subject — paired with ✗, never with red"},
	{Token: "--signal-critical-surface", Kind: BrandLossy, Target: "ColorSignalCriticalSurface", Note: "carries alpha in one theme; a terminal cell has no alpha channel, so the value is flattened against --background for that theme. Over a raised surface the browser resolves it lighter than this."},
	{Token: "--tracking-eyebrow", Kind: BrandExact, Target: "TrackingEyebrowEm", Note: "the eyebrow device is 'uppercase, tracked out'. Positive tracking survives a cell grid intact — the terminal's unit of tracking is one cell, so `ui.Eyebrow()` inserts a space between letters and the device reads the same"},
	{Token: "--dur-1", Kind: BrandExact, Target: "Dur1", Note: "a state swap on a control — the fastest honest tick"},
	{Token: "--dur-2", Kind: BrandExact, Target: "Dur2", Note: "the standard spinner frame interval"},
	{Token: "--dur-3", Kind: BrandExact, Target: "Dur3", Note: "a considered settle — a progress step"},
	{Token: "--dur-4", Kind: BrandExact, Target: "Dur4", Note: "a screen-level entrance"},
	{Token: "--ease", Kind: BrandNone, Target: "", Note: "a spinner has no easing curve. A terminal frame is a discrete redraw with no interpolated intermediate, so there is nothing for a cubic-bezier to shape — the CLI's cadence comes from --dur-* alone."},
	{Token: "--ease-out", Kind: BrandNone, Target: "", Note: "same as --ease: no interpolated frame to decelerate. An arrival in the terminal is one redraw."},
	{Token: "--ease-press", Kind: BrandNone, Target: "", Note: "same as --ease: no interpolated frame to accelerate. A press in the terminal is a keystroke and a redraw."},
	{Token: "--background", Kind: BrandExact, Target: "ColorBackground", Note: "the terminal's own ground"},
	{Token: "--foreground", Kind: BrandExact, Target: "ColorForeground", Note: "alias of --text-primary"},
	{Token: "--card", Kind: BrandExact, Target: "ColorCard", Note: "alias of --surface"},
	{Token: "--card-foreground", Kind: BrandExact, Target: "ColorCardForeground", Note: "alias of --text-primary"},
	{Token: "--popover", Kind: BrandExact, Target: "ColorPopover", Note: "alias of --surface-raised"},
	{Token: "--popover-foreground", Kind: BrandExact, Target: "ColorPopoverForeground", Note: "alias of --text-primary"},
	{Token: "--primary", Kind: BrandExact, Target: "ColorPrimary", Note: "alias of --ink"},
	{Token: "--primary-foreground", Kind: BrandExact, Target: "ColorPrimaryForeground", Note: "alias of --ink-foreground"},
	{Token: "--secondary", Kind: BrandExact, Target: "ColorSecondary", Note: "alias of --surface-muted"},
	{Token: "--secondary-foreground", Kind: BrandExact, Target: "ColorSecondaryForeground", Note: "alias of --text-primary"},
	{Token: "--muted", Kind: BrandExact, Target: "ColorMuted", Note: "alias of --surface-muted"},
	{Token: "--muted-foreground", Kind: BrandExact, Target: "ColorMutedForeground", Note: "alias of --text-secondary"},
	{Token: "--accent", Kind: BrandExact, Target: "ColorAccent", Note: "alias of --surface-muted"},
	{Token: "--accent-foreground", Kind: BrandExact, Target: "ColorAccentForeground", Note: "alias of --text-primary"},
	{Token: "--destructive", Kind: BrandExact, Target: "ColorDestructive", Note: "alias of --signal-critical — grayscale, paired with ✗"},
	{Token: "--border", Kind: BrandLossy, Target: "ColorBorder", Note: "carries alpha in one theme; a terminal cell has no alpha channel, so the value is flattened against --background for that theme. Over a raised surface the browser resolves it lighter than this."},
	{Token: "--input", Kind: BrandLossy, Target: "ColorInput", Note: "carries alpha in one theme; a terminal cell has no alpha channel, so the value is flattened against --background for that theme. Over a raised surface the browser resolves it lighter than this."},
	{Token: "--ring", Kind: BrandLossy, Target: "FocusMarker", Note: "a coloured outline around a control. A terminal cannot draw a ring around a cell run without stealing a row above and below, so focus is carried by a leading ▸ plus bold weight — the affordance survives, the geometry does not."},
	{Token: "--overlay", Kind: BrandNone, Target: "", Note: "the scrim behind a modal — a translucent black wash over the page. A terminal cannot dim what is behind a prompt: the cells either hold the prompt or hold what was there. huh redraws the region instead."},
	{Token: "--input-fill", Kind: BrandNone, Target: "", Note: "the fill of a bordered control, `transparent` in light and a 4.5% white lift in dark. A cell's background is either set or inherited; a lift that subtle lands on the same 256-colour index as the ground on most terminals, so projecting it would claim a difference nobody sees."},
	{Token: "--input-fill-hover", Kind: BrandNone, Target: "", Note: "the hover step of --input-fill. There is no hover in a terminal — the CLI's equivalent state is focus, and focus is carried by FocusMarker."},
	{Token: "--ring-invalid", Kind: BrandLossy, Target: "FocusInvalidMarker", Note: "the invalid-state ring. Same geometry loss as --ring, and the invalid state is carried by the ✗ glyph rather than by colour — the brand reads status by shape, never hue, so nothing is lost by the grayscale palette here."},
	{Token: "--chart-1", Kind: BrandNone, Target: "", Note: "TRIPWIRE — the CLI renders no charts today, so this projects to nothing. The FIRST chart written gets a projection here (a luminance-ordered ramp, read by lightness like the console's), not an inline colour at the call site."},
	{Token: "--chart-2", Kind: BrandNone, Target: "", Note: "TRIPWIRE — the CLI renders no charts today, so this projects to nothing. The FIRST chart written gets a projection here (a luminance-ordered ramp, read by lightness like the console's), not an inline colour at the call site."},
	{Token: "--chart-3", Kind: BrandNone, Target: "", Note: "TRIPWIRE — the CLI renders no charts today, so this projects to nothing. The FIRST chart written gets a projection here (a luminance-ordered ramp, read by lightness like the console's), not an inline colour at the call site."},
	{Token: "--chart-4", Kind: BrandNone, Target: "", Note: "TRIPWIRE — the CLI renders no charts today, so this projects to nothing. The FIRST chart written gets a projection here (a luminance-ordered ramp, read by lightness like the console's), not an inline colour at the call site."},
	{Token: "--chart-5", Kind: BrandNone, Target: "", Note: "TRIPWIRE — the CLI renders no charts today, so this projects to nothing. The FIRST chart written gets a projection here (a luminance-ordered ramp, read by lightness like the console's), not an inline colour at the call site."},
	{Token: "--sidebar", Kind: BrandNone, Target: "", Note: "the CLI has no persistent sidebar chrome; its navigation is the command tree, drawn per invocation. The inks this names are projected at --ink, --surface-muted and --text-primary."},
	{Token: "--sidebar-foreground", Kind: BrandNone, Target: "", Note: "the CLI has no persistent sidebar chrome; its navigation is the command tree, drawn per invocation. The inks this names are projected at --ink, --surface-muted and --text-primary."},
	{Token: "--sidebar-primary", Kind: BrandNone, Target: "", Note: "the CLI has no persistent sidebar chrome; its navigation is the command tree, drawn per invocation. The inks this names are projected at --ink, --surface-muted and --text-primary."},
	{Token: "--sidebar-primary-foreground", Kind: BrandNone, Target: "", Note: "the CLI has no persistent sidebar chrome; its navigation is the command tree, drawn per invocation. The inks this names are projected at --ink, --surface-muted and --text-primary."},
	{Token: "--sidebar-accent", Kind: BrandNone, Target: "", Note: "the CLI has no persistent sidebar chrome; its navigation is the command tree, drawn per invocation. The inks this names are projected at --ink, --surface-muted and --text-primary."},
	{Token: "--sidebar-accent-foreground", Kind: BrandNone, Target: "", Note: "the CLI has no persistent sidebar chrome; its navigation is the command tree, drawn per invocation. The inks this names are projected at --ink, --surface-muted and --text-primary."},
	{Token: "--sidebar-border", Kind: BrandNone, Target: "", Note: "the CLI has no persistent sidebar chrome; its navigation is the command tree, drawn per invocation. The inks this names are projected at --ink, --surface-muted and --text-primary."},
	{Token: "--sidebar-ring", Kind: BrandNone, Target: "", Note: "the CLI has no persistent sidebar chrome; its navigation is the command tree, drawn per invocation. The inks this names are projected at --ink, --surface-muted and --text-primary."},
	{Token: "--cl-len", Kind: BrandNone, Target: "", Note: "arm length in px of the [·] clamp's corner marks. The clamp is drawn from a masked border at sub-cell geometry; the terminal's focus affordance is FocusMarker (see --ring), which is a glyph, not a mark."},
	{Token: "--cl-gap", Kind: BrandNone, Target: "", Note: "how far outside the box the clamp's marks rest, in px. Sub-cell geometry; see --cl-len."},
	{Token: "--cl-reach", Kind: BrandNone, Target: "", Note: "the clamp's resting scale — an animated transform. Nothing in a terminal scales; see --cl-len and --ease."},
	{Token: "--cl-op", Kind: BrandNone, Target: "", Note: "the clamp's resting opacity. A cell has no alpha (see the composited colours above), and the clamp itself does not project; see --cl-len."},
	{Token: "--cl-ink", Kind: BrandNone, Target: "", Note: "the ink the clamp's marks are drawn in, overridable per control. The clamp does not project, so its ink has nothing to colour; see --cl-len."},
	{Token: "--z-sticky-head", Kind: BrandExact, Target: "LayerStickyHead", Note: "a sticky table header inside a scroll region"},
	{Token: "--z-raised", Kind: BrandExact, Target: "LayerRaised", Note: "table chrome, an overlapping badge"},
	{Token: "--z-sticky-bar", Kind: BrandExact, Target: "LayerStickyBar", Note: "an in-place action bar"},
	{Token: "--z-header", Kind: BrandExact, Target: "LayerHeader", Note: "the command's header band"},
	{Token: "--z-rail", Kind: BrandExact, Target: "LayerRail", Note: "the vertical edge rail"},
	{Token: "--z-grain", Kind: BrandExact, Target: "LayerGrain", Note: "the grain wash"},
	{Token: "--z-frame", Kind: BrandExact, Target: "LayerFrame", Note: "the hairline frame"},
	{Token: "--z-overlay", Kind: BrandExact, Target: "LayerOverlay", Note: "a prompt, a select, a confirm — huh's own surfaces"},
	{Token: "--z-overlay-nested", Kind: BrandExact, Target: "LayerOverlayNested", Note: "an overlay opened from inside another overlay"},
	{Token: "--z-toast", Kind: BrandExact, Target: "LayerToast", Note: "reports on everything above, so it outranks everything above"},
	{Token: "--frame-inset", Kind: BrandNone, Target: "", Note: "10px of air between the viewport edge and the hairline frame. The terminal's frame sits on the cell grid with no sub-cell inset to give it, and stealing a whole row and column for air would cost more than it buys on an 80-column screen."},
	{Token: "--text-display-lg", Kind: BrandLossy, Target: "EmphasisDisplay", Note: "56px. Every cell in a terminal is the same size, so a size ladder becomes a WEIGHT-and-CASE ladder: the largest step is bold + uppercase, the treatment that reads as 'this is the headline' with no size to spend."},
	{Token: "--text-display-md", Kind: BrandLossy, Target: "EmphasisHeading", Note: "40px. The middle step is bold alone — the second rung of the same ladder."},
	{Token: "--text-display-sm", Kind: BrandLossy, Target: "EmphasisBand", Note: "30px. The quietest display step is normal weight in primary ink; it is a heading only by contrast with the faint body around it."},
	{Token: "--text-display-xs", Kind: BrandLossy, Target: "EmphasisBand", Note: "24px — display voice rendered INSIDE the console shell: a plan name, a price, an onboarding or purchase heading. It collapses onto the SAME constant as --text-display-sm because the browser separates them by four pixels and a terminal cannot: both are the quiet display step, normal weight in primary ink, and inventing a fourth emphasis constant to carry a size difference the terminal has no cells to spend would publish a distinction the CLI cannot draw."},
	{Token: "--tracking-display", Kind: BrandNone, Target: "", Note: "negative tracking. The eyebrow's positive tracking projects because a cell can be ADDED; there is no sub-cell to remove, so tightening a display headline has nothing to spend."},
	{Token: "--leading-display", Kind: BrandNone, Target: "", Note: "line-height 0.96. A terminal row is one row; there is no leading to compress."},
	{Token: "--text-ui-3xs", Kind: BrandNone, Target: "", Note: "9px — a mono eyebrow or a badge caption, the smallest thing on a console screen. A terminal cell has one size, and the CLI's eyebrow device is already its own treatment (case and tracking, at --tracking-eyebrow); what makes this ink quiet in the console is --text-tertiary, which is projected exactly."},
	{Token: "--text-ui-2xs", Kind: BrandNone, Target: "", Note: "10px — a mono label over a value, or a column header. Same answer as --text-ui-3xs: the terminal separates a label from its value by INK and not by size, and that ink is projected exactly at --text-tertiary."},
	{Token: "--text-ui-xs", Kind: BrandNone, Target: "", Note: "11px — secondary metadata: a timestamp, a hint, a helper line. The console's most common rung, and in a terminal it is the same cell as the body it sits under; --text-secondary is what distinguishes it and is projected exactly."},
	{Token: "--text-ui-sm", Kind: BrandNone, Target: "", Note: "12px — control text: a chip, a filter, a small button. A terminal control is drawn from the same cells as everything else, so this rung buys the CLI nothing a border style and an ink do not already carry."},
	{Token: "--text-ui-md", Kind: BrandNone, Target: "", Note: "13px — the console's body rung, which in a terminal is simply the text. It is the size everything else is measured against, and the thing a terminal has exactly one of."},
	{Token: "--text-ui-lg", Kind: BrandLossy, Target: "EmphasisHeading", Note: "15px — the SECTION-HEADING rung (@repo/ui/section-heading renders it). With no size to spend, a heading in a terminal is bold, so this joins the weight ladder at the same rung --text-display-md takes: a console section heading and a marketing h2 are one treatment here, and the console's own step down from 15px to its 13px body is carried by weight rather than by size."},
	{Token: "--text-ui-xl", Kind: BrandLossy, Target: "EmphasisHeading", Note: "17px — the largest heading a console page carries, a dialog or sheet title. It collapses onto the SAME constant as --text-ui-lg because the terminal's ladder has three rungs and the console's has seven: bold is bold, and EmphasisDisplay is reserved for the display voice so a sheet title cannot arrive shouting in uppercase."},
	{Token: "--wrap-max", Kind: BrandNone, Target: "", Note: "1180px of maximum content width. The terminal's content width is the window's, reported by the tty and not ours to cap — a CLI that refused to use the width you gave it would be wrong."},
	{Token: "--wrap-pad", Kind: BrandNone, Target: "", Note: "64px of page gutter, sized to clear the vertical rail's glyphs. Terminal padding is measured in cells and set per style; there is no page to gutter."},
}

// BrandColor is a token's terminal ink: one sRGB hex per theme, which lipgloss binds to an
// AdaptiveColor. Values whose CSS carries alpha are already flattened against that theme's
// --background (a cell has no alpha channel), and those tokens are marked lossy above.
type BrandColor struct {
	Light string
	Dark  string
}

var (
	// ColorGray0 is --gray-0 · exact — ink ramp step
	ColorGray0 = BrandColor{Light: "#ffffff", Dark: "#ffffff"}

	// ColorGray25 is --gray-25 · exact — ink ramp step
	ColorGray25 = BrandColor{Light: "#fcfcfc", Dark: "#fcfcfc"}

	// ColorGray50 is --gray-50 · exact — ink ramp step
	ColorGray50 = BrandColor{Light: "#fafafa", Dark: "#fafafa"}

	// ColorGray100 is --gray-100 · exact — ink ramp step
	ColorGray100 = BrandColor{Light: "#f4f4f4", Dark: "#f4f4f4"}

	// ColorGray200 is --gray-200 · exact — ink ramp step
	ColorGray200 = BrandColor{Light: "#e7e7e7", Dark: "#e7e7e7"}

	// ColorGray300 is --gray-300 · exact — ink ramp step
	ColorGray300 = BrandColor{Light: "#d8d8d8", Dark: "#d8d8d8"}

	// ColorGray400 is --gray-400 · exact — ink ramp step
	ColorGray400 = BrandColor{Light: "#bababa", Dark: "#bababa"}

	// ColorGray500 is --gray-500 · exact — ink ramp step
	ColorGray500 = BrandColor{Light: "#939393", Dark: "#939393"}

	// ColorGray550 is --gray-550 · exact — ink ramp step
	ColorGray550 = BrandColor{Light: "#838383", Dark: "#838383"}

	// ColorGray600 is --gray-600 · exact — ink ramp step
	ColorGray600 = BrandColor{Light: "#737373", Dark: "#737373"}

	// ColorGray625 is --gray-625 · exact — ink ramp step
	ColorGray625 = BrandColor{Light: "#6b6b6b", Dark: "#6b6b6b"}

	// ColorGray700 is --gray-700 · exact — ink ramp step
	ColorGray700 = BrandColor{Light: "#525252", Dark: "#525252"}

	// ColorGray800 is --gray-800 · exact — ink ramp step
	ColorGray800 = BrandColor{Light: "#393939", Dark: "#393939"}

	// ColorGray900 is --gray-900 · exact — ink ramp step
	ColorGray900 = BrandColor{Light: "#262626", Dark: "#262626"}

	// ColorGray950 is --gray-950 · exact — ink ramp step
	ColorGray950 = BrandColor{Light: "#171717", Dark: "#171717"}

	// ColorGray1000 is --gray-1000 · exact — ink ramp step
	ColorGray1000 = BrandColor{Light: "#0e0e0e", Dark: "#0e0e0e"}

	// ColorGray1050 is --gray-1050 · exact — ink ramp step
	ColorGray1050 = BrandColor{Light: "#070707", Dark: "#070707"}

	// ColorGray1100 is --gray-1100 · exact — ink ramp step
	ColorGray1100 = BrandColor{Light: "#040404", Dark: "#040404"}

	// ColorBlack is --black · exact — the brand black — app icons, OG images, the PWA manifest
	ColorBlack = BrandColor{Light: "#020202", Dark: "#020202"}

	// ColorSurface is --surface · exact — the plate a panel is drawn on
	ColorSurface = BrandColor{Light: "#ffffff", Dark: "#0e0e0e"}

	// ColorSurfaceRaised is --surface-raised · exact — a panel lifted off the plate
	ColorSurfaceRaised = BrandColor{Light: "#ffffff", Dark: "#171717"}

	// ColorSurfaceSunken is --surface-sunken · exact — a well — a scroll region, a code block
	ColorSurfaceSunken = BrandColor{Light: "#f4f4f4", Dark: "#040404"}

	// ColorSurfaceMuted is --surface-muted · exact — a quiet fill — a selected row, an inactive
	// tab
	ColorSurfaceMuted = BrandColor{Light: "#f4f4f4", Dark: "#171717"}

	// ColorTextPrimary is --text-primary · exact — headings, values, emphasis — the CLI's
	// InkPrimary
	ColorTextPrimary = BrandColor{Light: "#0e0e0e", Dark: "#fafafa"}

	// ColorTextSecondary is --text-secondary · exact — body text — the CLI's InkSecondary
	ColorTextSecondary = BrandColor{Light: "#525252", Dark: "#939393"}

	// ColorTextTertiary is --text-tertiary · exact — labels and rules — the CLI's InkMuted
	ColorTextTertiary = BrandColor{Light: "#6b6b6b", Dark: "#838383"}

	// ColorTextDisabled is --text-disabled · exact — the dimmest readable ink — the CLI's InkFaint
	ColorTextDisabled = BrandColor{Light: "#bababa", Dark: "#525252"}

	// ColorTextOnInk is --text-on-ink · exact — foreground on an inverted (ink) surface — the
	// CLI's InkInverse
	ColorTextOnInk = BrandColor{Light: "#fafafa", Dark: "#0e0e0e"}

	// ColorBorderStrong is --border-strong · lossy — carries alpha in one theme; a terminal cell
	// has no alpha channel, so the value is flattened against --background for that theme. Over a
	// raised surface the browser resolves it lighter than this.
	ColorBorderStrong = BrandColor{Light: "#d8d8d8", Dark: "#313131"}

	// ColorBorderFaint is --border-faint · lossy — carries alpha in one theme; a terminal cell has
	// no alpha channel, so the value is flattened against --background for that theme. Over a
	// raised surface the browser resolves it lighter than this.
	ColorBorderFaint = BrandColor{Light: "#f4f4f4", Dark: "#141414"}

	// ColorInk is --ink · exact — the solid emphasis fill
	ColorInk = BrandColor{Light: "#171717", Dark: "#fafafa"}

	// ColorInkHover is --ink-hover · exact — its hover step; the CLI reuses it for a focused row's
	// fill
	ColorInkHover = BrandColor{Light: "#262626", Dark: "#e7e7e7"}

	// ColorInkForeground is --ink-foreground · exact — foreground on the ink fill
	ColorInkForeground = BrandColor{Light: "#fafafa", Dark: "#0e0e0e"}

	// ColorSignalStrong is --signal-strong · exact — an active/online subject
	ColorSignalStrong = BrandColor{Light: "#0e0e0e", Dark: "#fafafa"}

	// ColorSignalMute is --signal-mute · exact — a pending subject
	ColorSignalMute = BrandColor{Light: "#6b6b6b", Dark: "#838383"}

	// ColorSignalFaint is --signal-faint · exact — a disabled subject
	ColorSignalFaint = BrandColor{Light: "#bababa", Dark: "#525252"}

	// ColorSignalCritical is --signal-critical · exact — a failed subject — paired with ✗, never
	// with red
	ColorSignalCritical = BrandColor{Light: "#0e0e0e", Dark: "#fafafa"}

	// ColorSignalCriticalSurface is --signal-critical-surface · lossy — carries alpha in one
	// theme; a terminal cell has no alpha channel, so the value is flattened against --background
	// for that theme. Over a raised surface the browser resolves it lighter than this.
	ColorSignalCriticalSurface = BrandColor{Light: "#f4f4f4", Dark: "#1b1b1b"}

	// ColorBackground is --background · exact — the terminal's own ground
	ColorBackground = BrandColor{Light: "#fafafa", Dark: "#070707"}

	// ColorForeground is --foreground · exact — alias of --text-primary
	ColorForeground = BrandColor{Light: "#0e0e0e", Dark: "#fafafa"}

	// ColorCard is --card · exact — alias of --surface
	ColorCard = BrandColor{Light: "#ffffff", Dark: "#0e0e0e"}

	// ColorCardForeground is --card-foreground · exact — alias of --text-primary
	ColorCardForeground = BrandColor{Light: "#0e0e0e", Dark: "#fafafa"}

	// ColorPopover is --popover · exact — alias of --surface-raised
	ColorPopover = BrandColor{Light: "#ffffff", Dark: "#171717"}

	// ColorPopoverForeground is --popover-foreground · exact — alias of --text-primary
	ColorPopoverForeground = BrandColor{Light: "#0e0e0e", Dark: "#fafafa"}

	// ColorPrimary is --primary · exact — alias of --ink
	ColorPrimary = BrandColor{Light: "#171717", Dark: "#fafafa"}

	// ColorPrimaryForeground is --primary-foreground · exact — alias of --ink-foreground
	ColorPrimaryForeground = BrandColor{Light: "#fafafa", Dark: "#0e0e0e"}

	// ColorSecondary is --secondary · exact — alias of --surface-muted
	ColorSecondary = BrandColor{Light: "#f4f4f4", Dark: "#171717"}

	// ColorSecondaryForeground is --secondary-foreground · exact — alias of --text-primary
	ColorSecondaryForeground = BrandColor{Light: "#0e0e0e", Dark: "#fafafa"}

	// ColorMuted is --muted · exact — alias of --surface-muted
	ColorMuted = BrandColor{Light: "#f4f4f4", Dark: "#171717"}

	// ColorMutedForeground is --muted-foreground · exact — alias of --text-secondary
	ColorMutedForeground = BrandColor{Light: "#525252", Dark: "#939393"}

	// ColorAccent is --accent · exact — alias of --surface-muted
	ColorAccent = BrandColor{Light: "#f4f4f4", Dark: "#171717"}

	// ColorAccentForeground is --accent-foreground · exact — alias of --text-primary
	ColorAccentForeground = BrandColor{Light: "#0e0e0e", Dark: "#fafafa"}

	// ColorDestructive is --destructive · exact — alias of --signal-critical — grayscale, paired
	// with ✗
	ColorDestructive = BrandColor{Light: "#0e0e0e", Dark: "#fafafa"}

	// ColorBorder is --border · lossy — carries alpha in one theme; a terminal cell has no alpha
	// channel, so the value is flattened against --background for that theme. Over a raised
	// surface the browser resolves it lighter than this.
	ColorBorder = BrandColor{Light: "#e7e7e7", Dark: "#202020"}

	// ColorInput is --input · lossy — carries alpha in one theme; a terminal cell has no alpha
	// channel, so the value is flattened against --background for that theme. Over a raised
	// surface the browser resolves it lighter than this.
	ColorInput = BrandColor{Light: "#e7e7e7", Dark: "#2c2c2c"}
)

// BrandColors indexes the inks by token name. It is built FROM the vars above, so the table
// and the values cannot disagree — and a token deleted from the stylesheet takes its var with
// it, which is a compile error at every Go use site rather than a zero value at a map lookup.
var BrandColors = map[string]BrandColor{
	"--gray-0":                  ColorGray0,
	"--gray-25":                 ColorGray25,
	"--gray-50":                 ColorGray50,
	"--gray-100":                ColorGray100,
	"--gray-200":                ColorGray200,
	"--gray-300":                ColorGray300,
	"--gray-400":                ColorGray400,
	"--gray-500":                ColorGray500,
	"--gray-550":                ColorGray550,
	"--gray-600":                ColorGray600,
	"--gray-625":                ColorGray625,
	"--gray-700":                ColorGray700,
	"--gray-800":                ColorGray800,
	"--gray-900":                ColorGray900,
	"--gray-950":                ColorGray950,
	"--gray-1000":               ColorGray1000,
	"--gray-1050":               ColorGray1050,
	"--gray-1100":               ColorGray1100,
	"--black":                   ColorBlack,
	"--surface":                 ColorSurface,
	"--surface-raised":          ColorSurfaceRaised,
	"--surface-sunken":          ColorSurfaceSunken,
	"--surface-muted":           ColorSurfaceMuted,
	"--text-primary":            ColorTextPrimary,
	"--text-secondary":          ColorTextSecondary,
	"--text-tertiary":           ColorTextTertiary,
	"--text-disabled":           ColorTextDisabled,
	"--text-on-ink":             ColorTextOnInk,
	"--border-strong":           ColorBorderStrong,
	"--border-faint":            ColorBorderFaint,
	"--ink":                     ColorInk,
	"--ink-hover":               ColorInkHover,
	"--ink-foreground":          ColorInkForeground,
	"--signal-strong":           ColorSignalStrong,
	"--signal-mute":             ColorSignalMute,
	"--signal-faint":            ColorSignalFaint,
	"--signal-critical":         ColorSignalCritical,
	"--signal-critical-surface": ColorSignalCriticalSurface,
	"--background":              ColorBackground,
	"--foreground":              ColorForeground,
	"--card":                    ColorCard,
	"--card-foreground":         ColorCardForeground,
	"--popover":                 ColorPopover,
	"--popover-foreground":      ColorPopoverForeground,
	"--primary":                 ColorPrimary,
	"--primary-foreground":      ColorPrimaryForeground,
	"--secondary":               ColorSecondary,
	"--secondary-foreground":    ColorSecondaryForeground,
	"--muted":                   ColorMuted,
	"--muted-foreground":        ColorMutedForeground,
	"--accent":                  ColorAccent,
	"--accent-foreground":       ColorAccentForeground,
	"--destructive":             ColorDestructive,
	"--border":                  ColorBorder,
	"--input":                   ColorInput,
}

// BrandLayer is a stacking rung. This is the group that is worth MORE in the terminal than in
// the browser: bubbletea has no stacking context, so a view composites its children by hand and
// "the dropdown covers the panel covers the page" is otherwise re-decided at every call site,
// by argument order. Compare rungs; never hardcode a number.
type BrandLayer int

const (
	LayerStickyHead    BrandLayer = 10  // --z-sticky-head — a sticky table header inside a scroll region
	LayerRaised        BrandLayer = 20  // --z-raised — table chrome, an overlapping badge
	LayerStickyBar     BrandLayer = 30  // --z-sticky-bar — an in-place action bar
	LayerHeader        BrandLayer = 100 // --z-header — the command's header band
	LayerRail          BrandLayer = 110 // --z-rail — the vertical edge rail
	LayerGrain         BrandLayer = 120 // --z-grain — the grain wash
	LayerFrame         BrandLayer = 130 // --z-frame — the hairline frame
	LayerOverlay       BrandLayer = 200 // --z-overlay — a prompt, a select, a confirm — huh's own surfaces
	LayerOverlayNested BrandLayer = 210 // --z-overlay-nested — an overlay opened from inside another overlay
	LayerToast         BrandLayer = 300 // --z-toast — reports on everything above, so it outranks everything above
)

// BrandLayers indexes the rungs by token name.
var BrandLayers = map[string]BrandLayer{
	"--z-sticky-head":    LayerStickyHead,
	"--z-raised":         LayerRaised,
	"--z-sticky-bar":     LayerStickyBar,
	"--z-header":         LayerHeader,
	"--z-rail":           LayerRail,
	"--z-grain":          LayerGrain,
	"--z-frame":          LayerFrame,
	"--z-overlay":        LayerOverlay,
	"--z-overlay-nested": LayerOverlayNested,
	"--z-toast":          LayerToast,
}

// The motion vocabulary, as frame intervals. A duration is a duration: nothing is lost.
const (
	Dur1 = 120 * time.Millisecond // --dur-1 — a state swap on a control — the fastest honest tick
	Dur2 = 260 * time.Millisecond // --dur-2 — the standard spinner frame interval
	Dur3 = 420 * time.Millisecond // --dur-3 — a considered settle — a progress step
	Dur4 = 900 * time.Millisecond // --dur-4 — a screen-level entrance
)

// BrandDurations indexes the intervals by token name.
var BrandDurations = map[string]time.Duration{
	"--dur-1": Dur1,
	"--dur-2": Dur2,
	"--dur-3": Dur3,
	"--dur-4": Dur4,
}

const (
	// TrackingEyebrowEm is --tracking-eyebrow — the eyebrow device is 'uppercase, tracked out'.
	// Positive tracking survives a cell grid intact — the terminal's unit of tracking is one cell,
	// so `ui.Eyebrow()` inserts a space between letters and the device reads the same.
	TrackingEyebrowEm = 0.16
)

// EyebrowSeparator is what 0.16em of tracking becomes on a cell grid: one cell between
// letters. The terminal's unit of tracking is a whole cell, and the eyebrow device asks for
// letters pushed apart — so the device arrives intact even though the number cannot.
const EyebrowSeparator = " "

// Two border sets, and the collapse onto them is the single most visible thing this file
// decides. The console has six radii; a terminal cell has no sub-pixel, so a 2px and a 3px
// corner are the same square angle and there is nothing between "no corner" and "a corner". A
// reader who finds --radius-sm and --radius-md rendering identically is looking at a decision,
// not a bug.
type BrandBorder string

const (
	// BorderSquare is the terminal projection of: --radius-xs — 0 — no corner at all. ·
	// --radius-sm — 2px. A cell has no sub-pixel: below one cell's worth of corner there is
	// nothing the terminal can draw but a square angle. DELIBERATELY the same border as
	// --radius-md — that is not a bug to fix. · --radius-md — 3px. Same collapse as --radius-sm,
	// and deliberately identical to it.
	BorderSquare BrandBorder = "square"

	// BorderRounded is the terminal projection of: --radius-lg — 4px. From here up the console's
	// corner is legible, so the terminal spends its one rounded border set (╭╮╰╯) on it.
	// DELIBERATELY the same border as --radius-xl and --radius. · --radius-xl — 6px. Same collapse
	// as --radius-lg, and deliberately identical to it. · --radius — 0.25rem — the shadcn base
	// radius, 4px at the default root size. Same collapse as --radius-lg.
	BorderRounded BrandBorder = "rounded"
)

// BrandRadii is the six-to-two collapse, by token name.
var BrandRadii = map[string]BrandBorder{
	"--radius-xs": BorderSquare,
	"--radius-sm": BorderSquare,
	"--radius-md": BorderSquare,
	"--radius-lg": BorderRounded,
	"--radius-xl": BorderRounded,
	"--radius":    BorderRounded,
}

// The display type scale, collapsed onto a weight-and-case ladder. Every cell in a terminal is
// the same size, so a 56/40/30 size ladder cannot survive as sizes — what survives is the
// RANKING, and the terminal's ranking device is weight plus case plus ink.
type BrandEmphasis string

const (
	// EmphasisDisplay is the terminal projection of: --text-display-lg — 56px. Every cell in a
	// terminal is the same size, so a size ladder becomes a WEIGHT-and-CASE ladder: the largest
	// step is bold + uppercase, the treatment that reads as 'this is the headline' with no size to
	// spend.
	EmphasisDisplay BrandEmphasis = "display"

	// EmphasisHeading is the terminal projection of: --text-display-md — 40px. The middle step is
	// bold alone — the second rung of the same ladder. · --text-ui-lg — 15px — the SECTION-HEADING
	// rung (@repo/ui/section-heading renders it). With no size to spend, a heading in a terminal
	// is bold, so this joins the weight ladder at the same rung --text-display-md takes: a console
	// section heading and a marketing h2 are one treatment here, and the console's own step down
	// from 15px to its 13px body is carried by weight rather than by size. · --text-ui-xl — 17px —
	// the largest heading a console page carries, a dialog or sheet title. It collapses onto the
	// SAME constant as --text-ui-lg because the terminal's ladder has three rungs and the
	// console's has seven: bold is bold, and EmphasisDisplay is reserved for the display voice so
	// a sheet title cannot arrive shouting in uppercase.
	EmphasisHeading BrandEmphasis = "heading"

	// EmphasisBand is the terminal projection of: --text-display-sm — 30px. The quietest display
	// step is normal weight in primary ink; it is a heading only by contrast with the faint body
	// around it. · --text-display-xs — 24px — display voice rendered INSIDE the console shell: a
	// plan name, a price, an onboarding or purchase heading. It collapses onto the SAME constant
	// as --text-display-sm because the browser separates them by four pixels and a terminal
	// cannot: both are the quiet display step, normal weight in primary ink, and inventing a
	// fourth emphasis constant to carry a size difference the terminal has no cells to spend would
	// publish a distinction the CLI cannot draw.
	EmphasisBand BrandEmphasis = "band"
)

// BrandEmphasisLadder is the size-to-weight collapse, by token name.
var BrandEmphasisLadder = map[string]BrandEmphasis{
	"--text-display-lg": EmphasisDisplay,
	"--text-display-md": EmphasisHeading,
	"--text-display-sm": EmphasisBand,
	"--text-display-xs": EmphasisBand,
	"--text-ui-lg":      EmphasisHeading,
	"--text-ui-xl":      EmphasisHeading,
}

// The focus ring, which is not a ring. A terminal cannot outline a run of cells without
// stealing the row above and below it, so focus is a leading marker plus bold weight. The
// affordance survives; the geometry does not. Invalid is carried by the glyph, per the brand's
// "status by shape, never hue" rule — so nothing further is lost to the grayscale palette.
const (
	// FocusMarker is the terminal projection of: --ring — a coloured outline around a control. A
	// terminal cannot draw a ring around a cell run without stealing a row above and below, so
	// focus is carried by a leading ▸ plus bold weight — the affordance survives, the geometry
	// does not.
	FocusMarker = "▸"

	// FocusInvalidMarker is the terminal projection of: --ring-invalid — the invalid-state ring.
	// Same geometry loss as --ring, and the invalid state is carried by the ✗ glyph rather than by
	// colour — the brand reads status by shape, never hue, so nothing is lost by the grayscale
	// palette here.
	FocusInvalidMarker = "✗"
)

// BrandFocusMarkers is the ring-to-marker collapse, by token name.
var BrandFocusMarkers = map[string]string{
	"--ring":         FocusMarker,
	"--ring-invalid": FocusInvalidMarker,
}
