// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by apps/console/scripts/gen-go-enums.ts; DO NOT EDIT.
// Regenerate with: pnpm -C apps/console run gen:go-enums
//
// These mirror the drizzle enum SSOT (apps/console/lib/db/schema/enums.ts). Reference
// the constants (not bare strings) in Go so a removed enum value fails to compile and a
// new one is caught by the exhaustive linter + coverage tests.

package types

// JobType mirrors the provision_job_type enum (lib/db/schema/enums.ts).
type JobType string

const (
	JobTypeDestroyRunner JobType = "DESTROY_RUNNER"
	JobTypeDeploy        JobType = "DEPLOY"
	JobTypeDestroy       JobType = "DESTROY"
	JobTypePlan          JobType = "PLAN"
	JobTypeDeployRunner  JobType = "DEPLOY_RUNNER"
	JobTypeUpdateRunner  JobType = "UPDATE_RUNNER"
	JobTypeAnalyzeRepo   JobType = "ANALYZE_REPO"
	JobTypeDetectDrift   JobType = "DETECT_DRIFT"
	JobTypeAudit         JobType = "AUDIT"
	JobTypeChartScan     JobType = "CHART_SCAN"
	JobTypeIacScan       JobType = "IAC_SCAN"
	JobTypeStateSurgery  JobType = "STATE_SURGERY"
	JobTypeProbeCluster  JobType = "PROBE_CLUSTER"
	JobTypeBuild         JobType = "BUILD"
)

// AllJobTypes is every provision_job_type value, in schema order.
var AllJobTypes = []JobType{
	JobTypeDestroyRunner,
	JobTypeDeploy,
	JobTypeDestroy,
	JobTypePlan,
	JobTypeDeployRunner,
	JobTypeUpdateRunner,
	JobTypeAnalyzeRepo,
	JobTypeDetectDrift,
	JobTypeAudit,
	JobTypeChartScan,
	JobTypeIacScan,
	JobTypeStateSurgery,
	JobTypeProbeCluster,
	JobTypeBuild,
}

// JobStatus mirrors the provision_job_status enum (lib/db/schema/enums.ts).
type JobStatus string

const (
	JobStatusQueued     JobStatus = "QUEUED"
	JobStatusClaimed    JobStatus = "CLAIMED"
	JobStatusProcessing JobStatus = "PROCESSING"
	JobStatusSuccess    JobStatus = "SUCCESS"
	JobStatusFailed     JobStatus = "FAILED"
	JobStatusCancelled  JobStatus = "CANCELLED"
)

// AllJobStatuses is every provision_job_status value, in schema order.
var AllJobStatuses = []JobStatus{
	JobStatusQueued,
	JobStatusClaimed,
	JobStatusProcessing,
	JobStatusSuccess,
	JobStatusFailed,
	JobStatusCancelled,
}

// CloudProvider mirrors the cloud_provider enum (lib/db/schema/enums.ts).
type CloudProvider string

const (
	CloudProviderAws          CloudProvider = "aws"
	CloudProviderAzure        CloudProvider = "azure"
	CloudProviderGcp          CloudProvider = "gcp"
	CloudProviderAlibaba      CloudProvider = "alibaba"
	CloudProviderDigitalocean CloudProvider = "digitalocean"
	CloudProviderHetzner      CloudProvider = "hetzner"
	CloudProviderCivo         CloudProvider = "civo"
)

// AllCloudProviders is every cloud_provider value, in schema order.
var AllCloudProviders = []CloudProvider{
	CloudProviderAws,
	CloudProviderAzure,
	CloudProviderGcp,
	CloudProviderAlibaba,
	CloudProviderDigitalocean,
	CloudProviderHetzner,
	CloudProviderCivo,
}

// EnvironmentStage mirrors the environment_stage enum (lib/db/schema/enums.ts).
type EnvironmentStage string

const (
	EnvironmentStageDevelopment EnvironmentStage = "development"
	EnvironmentStageStaging     EnvironmentStage = "staging"
	EnvironmentStageProduction  EnvironmentStage = "production"
)

// AllEnvironmentStages is every environment_stage value, in schema order.
var AllEnvironmentStages = []EnvironmentStage{
	EnvironmentStageDevelopment,
	EnvironmentStageStaging,
	EnvironmentStageProduction,
}

// ProjectStatus mirrors the project_status enum (lib/db/schema/enums.ts).
type ProjectStatus string

const (
	ProjectStatusDraft        ProjectStatus = "DRAFT"
	ProjectStatusQueued       ProjectStatus = "QUEUED"
	ProjectStatusProvisioning ProjectStatus = "PROVISIONING"
	ProjectStatusActive       ProjectStatus = "ACTIVE"
	ProjectStatusFailed       ProjectStatus = "FAILED"
	ProjectStatusDestroying   ProjectStatus = "DESTROYING"
	ProjectStatusDestroyed    ProjectStatus = "DESTROYED"
)

// AllProjectStatuses is every project_status value, in schema order.
var AllProjectStatuses = []ProjectStatus{
	ProjectStatusDraft,
	ProjectStatusQueued,
	ProjectStatusProvisioning,
	ProjectStatusActive,
	ProjectStatusFailed,
	ProjectStatusDestroying,
	ProjectStatusDestroyed,
}

// PlacementMode mirrors the placement_mode enum (lib/db/schema/enums.ts).
type PlacementMode string

const (
	PlacementModeNamespace PlacementMode = "namespace"
	PlacementModeVcluster  PlacementMode = "vcluster"
	PlacementModeDedicated PlacementMode = "dedicated"
)

// AllPlacementModes is every placement_mode value, in schema order.
var AllPlacementModes = []PlacementMode{
	PlacementModeNamespace,
	PlacementModeVcluster,
	PlacementModeDedicated,
}

// ServiceWorkloadType mirrors the service_workload_type enum (lib/db/schema/enums.ts).
type ServiceWorkloadType string

const (
	ServiceWorkloadTypeDeployment  ServiceWorkloadType = "deployment"
	ServiceWorkloadTypeJob         ServiceWorkloadType = "job"
	ServiceWorkloadTypeCronjob     ServiceWorkloadType = "cronjob"
	ServiceWorkloadTypeStatefulset ServiceWorkloadType = "statefulset"
)

// AllServiceWorkloadTypes is every service_workload_type value, in schema order.
var AllServiceWorkloadTypes = []ServiceWorkloadType{
	ServiceWorkloadTypeDeployment,
	ServiceWorkloadTypeJob,
	ServiceWorkloadTypeCronjob,
	ServiceWorkloadTypeStatefulset,
}

// ChartWorkloadKind mirrors the chart_workload_kind enum (lib/db/schema/enums.ts).
type ChartWorkloadKind string

const (
	ChartWorkloadKindDeployment  ChartWorkloadKind = "deployment"
	ChartWorkloadKindStatefulset ChartWorkloadKind = "statefulset"
	ChartWorkloadKindDaemonset   ChartWorkloadKind = "daemonset"
	ChartWorkloadKindCronjob     ChartWorkloadKind = "cronjob"
	ChartWorkloadKindJob         ChartWorkloadKind = "job"
)

// AllChartWorkloadKinds is every chart_workload_kind value, in schema order.
var AllChartWorkloadKinds = []ChartWorkloadKind{
	ChartWorkloadKindDeployment,
	ChartWorkloadKindStatefulset,
	ChartWorkloadKindDaemonset,
	ChartWorkloadKindCronjob,
	ChartWorkloadKindJob,
}

// NosqlKeyType mirrors the nosql_key_type enum (lib/db/schema/enums.ts).
type NosqlKeyType string

const (
	NosqlKeyTypeS NosqlKeyType = "S"
	NosqlKeyTypeN NosqlKeyType = "N"
	NosqlKeyTypeB NosqlKeyType = "B"
)

// AllNosqlKeyTypes is every nosql_key_type value, in schema order.
var AllNosqlKeyTypes = []NosqlKeyType{
	NosqlKeyTypeS,
	NosqlKeyTypeN,
	NosqlKeyTypeB,
}

// NosqlTableType mirrors the nosql_table_type enum (lib/db/schema/enums.ts).
type NosqlTableType string

const (
	NosqlTableTypeStandard NosqlTableType = "standard"
	NosqlTableTypeGlobal   NosqlTableType = "global"
)

// AllNosqlTableTypes is every nosql_table_type value, in schema order.
var AllNosqlTableTypes = []NosqlTableType{
	NosqlTableTypeStandard,
	NosqlTableTypeGlobal,
}

// NosqlCapacityMode mirrors the nosql_capacity_mode enum (lib/db/schema/enums.ts).
type NosqlCapacityMode string

const (
	NosqlCapacityModeOnDemand    NosqlCapacityMode = "on_demand"
	NosqlCapacityModeProvisioned NosqlCapacityMode = "provisioned"
)

// AllNosqlCapacityModes is every nosql_capacity_mode value, in schema order.
var AllNosqlCapacityModes = []NosqlCapacityMode{
	NosqlCapacityModeOnDemand,
	NosqlCapacityModeProvisioned,
}

// CacheEngine mirrors the cache_engine enum (lib/db/schema/enums.ts).
type CacheEngine string

const (
	CacheEngineRedis  CacheEngine = "redis"
	CacheEngineValkey CacheEngine = "valkey"
)

// AllCacheEngines is every cache_engine value, in schema order.
var AllCacheEngines = []CacheEngine{
	CacheEngineRedis,
	CacheEngineValkey,
}

// ServiceBindingKind mirrors the service_binding_kind enum (lib/db/schema/enums.ts).
type ServiceBindingKind string

const (
	ServiceBindingKindDatabase ServiceBindingKind = "database"
	ServiceBindingKindCache    ServiceBindingKind = "cache"
	ServiceBindingKindQueue    ServiceBindingKind = "queue"
	ServiceBindingKindSecret   ServiceBindingKind = "secret"
)

// AllServiceBindingKinds is every service_binding_kind value, in schema order.
var AllServiceBindingKinds = []ServiceBindingKind{
	ServiceBindingKindDatabase,
	ServiceBindingKindCache,
	ServiceBindingKindQueue,
	ServiceBindingKindSecret,
}

// ServiceBindingFacet mirrors the service_binding_facet enum (lib/db/schema/enums.ts).
type ServiceBindingFacet string

const (
	ServiceBindingFacetEndpoint         ServiceBindingFacet = "endpoint"
	ServiceBindingFacetPort             ServiceBindingFacet = "port"
	ServiceBindingFacetUsername         ServiceBindingFacet = "username"
	ServiceBindingFacetPassword         ServiceBindingFacet = "password"
	ServiceBindingFacetConnectionString ServiceBindingFacet = "connection_string"
	ServiceBindingFacetValue            ServiceBindingFacet = "value"
)

// AllServiceBindingFacets is every service_binding_facet value, in schema order.
var AllServiceBindingFacets = []ServiceBindingFacet{
	ServiceBindingFacetEndpoint,
	ServiceBindingFacetPort,
	ServiceBindingFacetUsername,
	ServiceBindingFacetPassword,
	ServiceBindingFacetConnectionString,
	ServiceBindingFacetValue,
}

// TopicSubscriptionProtocol mirrors the topic_subscription_protocol enum (lib/db/schema/enums.ts).
type TopicSubscriptionProtocol string

const (
	TopicSubscriptionProtocolHttps  TopicSubscriptionProtocol = "https"
	TopicSubscriptionProtocolSqs    TopicSubscriptionProtocol = "sqs"
	TopicSubscriptionProtocolEmail  TopicSubscriptionProtocol = "email"
	TopicSubscriptionProtocolLambda TopicSubscriptionProtocol = "lambda"
)

// AllTopicSubscriptionProtocols is every topic_subscription_protocol value, in schema order.
var AllTopicSubscriptionProtocols = []TopicSubscriptionProtocol{
	TopicSubscriptionProtocolHttps,
	TopicSubscriptionProtocolSqs,
	TopicSubscriptionProtocolEmail,
	TopicSubscriptionProtocolLambda,
}

// AddonMode mirrors the addon_mode enum (lib/db/schema/enums.ts).
type AddonMode string

const (
	AddonModeManaged AddonMode = "managed"
	AddonModeGitops  AddonMode = "gitops"
)

// AllAddonModes is every addon_mode value, in schema order.
var AllAddonModes = []AddonMode{
	AddonModeManaged,
	AddonModeGitops,
}

// AlertChannelType mirrors the alert_channel_type enum (lib/db/schema/enums.ts).
type AlertChannelType string

const (
	AlertChannelTypeWebhook    AlertChannelType = "webhook"
	AlertChannelTypeEmail      AlertChannelType = "email"
	AlertChannelTypeSlack      AlertChannelType = "slack"
	AlertChannelTypeRocketchat AlertChannelType = "rocketchat"
	AlertChannelTypeDiscord    AlertChannelType = "discord"
	AlertChannelTypeTeams      AlertChannelType = "teams"
	AlertChannelTypeMattermost AlertChannelType = "mattermost"
	AlertChannelTypeGooglechat AlertChannelType = "googlechat"
	AlertChannelTypePagerduty  AlertChannelType = "pagerduty"
)

// AllAlertChannelTypes is every alert_channel_type value, in schema order.
var AllAlertChannelTypes = []AlertChannelType{
	AlertChannelTypeWebhook,
	AlertChannelTypeEmail,
	AlertChannelTypeSlack,
	AlertChannelTypeRocketchat,
	AlertChannelTypeDiscord,
	AlertChannelTypeTeams,
	AlertChannelTypeMattermost,
	AlertChannelTypeGooglechat,
	AlertChannelTypePagerduty,
}

// AlertSeverity mirrors the alert_severity enum (lib/db/schema/enums.ts).
type AlertSeverity string

const (
	AlertSeverityInfo     AlertSeverity = "info"
	AlertSeverityWarning  AlertSeverity = "warning"
	AlertSeverityCritical AlertSeverity = "critical"
)

// AllAlertSeveritys is every alert_severity value, in schema order.
var AllAlertSeveritys = []AlertSeverity{
	AlertSeverityInfo,
	AlertSeverityWarning,
	AlertSeverityCritical,
}
