// SPDX-FileCopyrightText: 2026 Alethia Labs <legal@alethialabs.io>
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by apps/console/scripts/gen-go-vocab.ts; DO NOT EDIT.
// Regenerate with: pnpm -C apps/console run gen:go-vocab
//
// Source of truth: packages/ui/src/status-badge.tsx (the words and their tiers), apps/console/lib/db/schema
// (their provenance) and apps/console/scripts/lib/status-vocab.ts (the terminal projection).
//
// This is the ONE status vocabulary. Before it, apps/cli/pkg/utils/ui/styles.go decided a status
// glyph from nine uppercase words and a default arm, with no case folding, against a console map
// of 33 lower-cased keys — so the two surfaces disagreed on seven measured cases and
// six pgEnums that shout on the wire missed every arm of the switch. The CLI now reads this file
// and decides nothing.
//
// PROVENANCE IS EMITTED, and that is the point of the file rather than a decoration. 27 of the
// 33 words are a drizzle enum value; 6 are in NO pgEnum and carry the declared origin
// instead. The generator refuses to emit a word that can say neither, because a vocabulary with
// no single owner drifts by OMISSION — a word nobody can account for looks exactly like one
// everybody agreed on.
//
// WHAT IS STILL WRONG, counted rather than hidden: StatusVocabularyGaps below holds 24 values
// across 9 status-bearing enums that this vocabulary has no word for. Every one of them resolves
// to StatusTierIdle — "present but not doing anything" — on BOTH surfaces, which for an approved
// promotion or a blocked one is wrong in the same way on both. Fixing that is a vocabulary
// decision, not a rendering one, and it does not belong to the generator.

package types

import "strings"

// StatusTier is the grayscale visual tier a status resolves to. State reads through glyph shape
// and ink weight, never hue.
type StatusTier string

const (
	StatusTierActive   StatusTier = "active"
	StatusTierPending  StatusTier = "pending"
	StatusTierIdle     StatusTier = "idle"
	StatusTierFailed   StatusTier = "failed"
	StatusTierDisabled StatusTier = "disabled"
	StatusTierLive     StatusTier = "live"
)

// AllStatusTiers is every tier, in the order packages/ui/src/status-badge.tsx declares them.
var AllStatusTiers = []StatusTier{
	StatusTierActive,
	StatusTierPending,
	StatusTierIdle,
	StatusTierFailed,
	StatusTierDisabled,
	StatusTierLive,
}

// StatusTierFallback is what an unrecognised status resolves to.
//
// It mirrors statusTier()'s fallback exactly, INCLUDING its silence. The console warns once per
// unknown status in development; a CLI has no equivalent moment, so the honest place to look for
// what this is swallowing is StatusVocabularyGaps at the bottom of this file.
const StatusTierFallback = StatusTierIdle

// The terminal projection of each tier. The em dash appears nowhere here on purpose: it is the
// empty-value sentinel (format.Dash), and a status drawn as the dash is indistinguishable from a
// cell nobody could fill.
const (
	// StatusGlyphActive — filled — running, healthy, or finished well.
	StatusGlyphActive = "●"

	// StatusGlyphPending — half-filled — in flight; something is happening and this is not its final
	// answer.
	StatusGlyphPending = "◐"

	// StatusGlyphIdle — hollow — present, reachable, and not doing anything.
	StatusGlyphIdle = "○"

	// StatusGlyphFailed — the brand's failure shape; the grayscale palette carries no red, so failure
	// reads by shape and never by hue.
	StatusGlyphFailed = "✗"

	// StatusGlyphDisabled — a dotted outline — the shape is still there and nothing is in it: gone,
	// inert or skipped. NOT the em dash, which means we could not fill the cell at all, and NOT the
	// middot, which is ui.SymbolBullet, the separator inside a picker label.
	StatusGlyphDisabled = "◌"

	// StatusGlyphLive — the console blinks a live subject; a terminal cell cannot blink, so `live`
	// arrives as an ordinary active dot and the 'still under examination' half of the meaning is lost.
	// It is deliberately the same glyph as StatusGlyphActive.
	StatusGlyphLive = "●"
)

// StatusGlyphs indexes the glyphs by tier. It is built FROM the constants above, so the table and
// the values cannot disagree.
var StatusGlyphs = map[StatusTier]string{
	StatusTierActive:   StatusGlyphActive,
	StatusTierPending:  StatusGlyphPending,
	StatusTierIdle:     StatusGlyphIdle,
	StatusTierFailed:   StatusGlyphFailed,
	StatusTierDisabled: StatusGlyphDisabled,
	StatusTierLive:     StatusGlyphLive,
}

// StatusProvenance says what accounts for a word being in the vocabulary at all.
type StatusProvenance string

const (
	// StatusFromEnum — a drizzle pgEnum spells this word; Sources names every enum and value.
	StatusFromEnum StatusProvenance = "enum"
	// StatusFromWire — no pgEnum has it. Sources holds the single declared origin, which may itself
	// be the statement that nothing emits the word at all.
	StatusFromWire StatusProvenance = "wire"
)

// StatusWord is one entry of the vocabulary, with everything known about where it came from.
type StatusWord struct {
	Status     string
	Tier       StatusTier
	Provenance StatusProvenance
	Sources    []string
	// Note records a decision where the two surfaces used to disagree, so the terminal's change
	// of behaviour is reviewable rather than archaeological. Empty for a word nobody argued about.
	Note string
}

// StatusVocabulary is every word, in the order packages/ui/src/status-badge.tsx declares them — which is grouped by
// tier, so a reordering there is a diff somebody has to look at here.
var StatusVocabulary = []StatusWord{
	{Status: "active", Tier: StatusTierActive, Provenance: StatusFromEnum,
		Sources: []string{"billing_status.active", "commerce_order_state.active", "component_status.ACTIVE", "connector_status.active", "project_status.ACTIVE", "signing_key_status.active"},
		Note:    ""},
	{Status: "online", Tier: StatusTierActive, Provenance: StatusFromEnum,
		Sources: []string{"runner_status.ONLINE"},
		Note:    ""},
	{Status: "success", Tier: StatusTierActive, Provenance: StatusFromEnum,
		Sources: []string{"provision_job_status.SUCCESS"},
		Note:    "One word had three renderings inside one product: ○ in `jobs list`, bold text via formatJobStatus in `job wait`, and a filled active dot in the console. It is ● everywhere now, and formatJobStatus is deleted."},
	{Status: "succeeded", Tier: StatusTierActive, Provenance: StatusFromEnum,
		Sources: []string{"promotion_status.SUCCEEDED"},
		Note:    ""},
	{Status: "approved", Tier: StatusTierActive, Provenance: StatusFromEnum,
		Sources: []string{"approval_status.approved", "promotion_status.APPROVED"},
		Note:    "promotion_status.APPROVED and approval_status.approved. Read as ACTIVE rather than pending: on an approval slot the word is terminal and positive — that person decided, and decided yes — and on a promotion it means the gates are satisfied. `pending` would be defensible for the promotion (it is a cleared waypoint, the deploy has not run) and is plainly wrong for the slot; one word gets one tier, so it takes the reading that is never wrong. It drew ○, the idle glyph, until #4117."},
	{Status: "ready", Tier: StatusTierActive, Provenance: StatusFromWire,
		Sources: []string{"the wire status of an add-on, an IaC source and a chart source (api.Addon, api.IacSource, api.ChartSource) — a text column, not a pgEnum, so nothing constrains it"},
		Note:    ""},
	{Status: "connected", Tier: StatusTierActive, Provenance: StatusFromEnum,
		Sources: []string{"cloud_identity_status.connected"},
		Note:    ""},
	{Status: "running", Tier: StatusTierActive, Provenance: StatusFromWire,
		Sources: []string{"the agent panes' local phase union (components/agent/approval-card.tsx) and the ordinary Kubernetes word for a workload that is up; no column holds it"},
		Note:    ""},
	{Status: "queued", Tier: StatusTierPending, Provenance: StatusFromEnum,
		Sources: []string{"project_status.QUEUED", "provision_job_status.QUEUED"},
		Note:    ""},
	{Status: "pending", Tier: StatusTierPending, Provenance: StatusFromEnum,
		Sources: []string{"alert_delivery_status.pending", "approval_status.pending", "cloud_identity_status.pending", "component_status.PENDING"},
		Note:    "Go had no case for the literal word and defaulted it to ○. component_status.PENDING is the pending tier."},
	{Status: "pending_plan", Tier: StatusTierPending, Provenance: StatusFromEnum,
		Sources: []string{"promotion_status.PENDING_PLAN"},
		Note:    "promotion_status.PENDING_PLAN — the candidate is written and a PLAN job is queued. Genuinely in flight, so the pending tier, exactly as `queued` is. It drew ○ until #4117."},
	{Status: "pending_approval", Tier: StatusTierPending, Provenance: StatusFromEnum,
		Sources: []string{"promotion_status.PENDING_APPROVAL"},
		Note:    "promotion_status.PENDING_APPROVAL — gates need a human. The pending tier's own definition, 'in flight; something is happening and this is not its final answer', and the word is literally `pending`. It drew ○ until #4117."},
	{Status: "processing", Tier: StatusTierPending, Provenance: StatusFromEnum,
		Sources: []string{"provision_job_status.PROCESSING", "stripe_webhook_event_status.processing"},
		Note:    "Go defaulted it to ○ (idle) and inked it differently from CLAIMED for no stated reason; both are pending, ◐."},
	{Status: "claimed", Tier: StatusTierPending, Provenance: StatusFromEnum,
		Sources: []string{"provision_job_status.CLAIMED"},
		Note:    "Same as processing — a claimed job has a runner and is about to start, which is the pending tier, not the idle one."},
	{Status: "provisioning", Tier: StatusTierPending, Provenance: StatusFromEnum,
		Sources: []string{"project_status.PROVISIONING"},
		Note:    ""},
	{Status: "creating", Tier: StatusTierPending, Provenance: StatusFromEnum,
		Sources: []string{"component_status.CREATING"},
		Note:    ""},
	{Status: "updating", Tier: StatusTierPending, Provenance: StatusFromEnum,
		Sources: []string{"component_status.UPDATING"},
		Note:    ""},
	{Status: "deploying", Tier: StatusTierPending, Provenance: StatusFromEnum,
		Sources: []string{"promotion_status.DEPLOYING"},
		Note:    ""},
	{Status: "destroying", Tier: StatusTierPending, Provenance: StatusFromEnum,
		Sources: []string{"component_status.DESTROYING", "project_status.DESTROYING"},
		Note:    "Go defaulted it to ○ while CREATING, UPDATING and PROVISIONING were ◐ — the same kind of work, drawn two ways depending on which word the wire happened to use."},
	{Status: "idle", Tier: StatusTierIdle, Provenance: StatusFromWire,
		Sources: []string{"the tier's own name, reused as a word: the runner widget reports a runner as `idle` (components/widgets) where runner_status has only ONLINE/OFFLINE/DRAINING"},
		Note:    ""},
	{Status: "offline", Tier: StatusTierIdle, Provenance: StatusFromEnum,
		Sources: []string{"runner_status.OFFLINE"},
		Note:    ""},
	{Status: "draining", Tier: StatusTierIdle, Provenance: StatusFromEnum,
		Sources: []string{"runner_status.DRAINING"},
		Note:    "CONTESTED, and the console wins by default rather than by argument. Go drew ◐ (in progress); this vocabulary says idle, whose own comment reads 'present but not doing anything'. A draining runner is finishing the work it holds and refusing new work, which is not nothing — so the CLI's answer was arguably the better one and this generator takes it away. The one-line fix is `draining: \"pending\"` in STATUS_TIER, which changes what the CONSOLE renders and is therefore a vocabulary decision, not this generator's. See #3660 case 1."},
	{Status: "draft", Tier: StatusTierIdle, Provenance: StatusFromEnum,
		Sources: []string{"project_status.DRAFT"},
		Note:    ""},
	{Status: "cancelled", Tier: StatusTierIdle, Provenance: StatusFromEnum,
		Sources: []string{"commerce_order_state.cancelled", "promotion_status.CANCELLED", "provision_job_status.CANCELLED"},
		Note:    ""},
	{Status: "canceled", Tier: StatusTierIdle, Provenance: StatusFromEnum,
		Sources: []string{"billing_status.canceled"},
		Note:    ""},
	{Status: "failed", Tier: StatusTierFailed, Provenance: StatusFromEnum,
		Sources: []string{"alert_delivery_status.failed", "cloud_identity_status.failed", "component_status.FAILED", "connector_health_status.failed", "project_status.FAILED", "promotion_status.FAILED", "provision_job_status.FAILED"},
		Note:    ""},
	{Status: "error", Tier: StatusTierFailed, Provenance: StatusFromEnum,
		Sources: []string{"stripe_webhook_event_status.error"},
		Note:    ""},
	{Status: "errored", Tier: StatusTierFailed, Provenance: StatusFromWire,
		Sources: []string{"NOTHING EMITS THIS. A past-tense alias of `failed`, kept because it is a word a hand-written wire status reaches for; it appears in packages/ui/tests/status-badge.test.tsx and nowhere else in the product. Delete it if a census ever proves it unreachable"},
		Note:    ""},
	{Status: "rejected", Tier: StatusTierFailed, Provenance: StatusFromEnum,
		Sources: []string{"approval_status.rejected"},
		Note:    "approval_status.rejected. The failed tier: a rejection is terminal and negative, and it is the reason a promotion is not moving. It drew ○ until #4117, identically to `approved` one row above it."},
	{Status: "blocked", Tier: StatusTierFailed, Provenance: StatusFromEnum,
		Sources: []string{"promotion_status.BLOCKED"},
		Note:    "promotion_status.BLOCKED — 'a hard gate failed (predecessor unhealthy / verify hard-fail)'. The failed tier, for the same reason `failed` is: it is terminal, it is negative, and it is the row an operator has to act on. It drew ○ until #4117."},
	{Status: "disabled", Tier: StatusTierDisabled, Provenance: StatusFromWire,
		Sources: []string{"the tier's own name, reused as a word for an alert rule, channel or SSO provider whose `enabled` column is false — a boolean, rendered as a status"},
		Note:    ""},
	{Status: "destroyed", Tier: StatusTierDisabled, Provenance: StatusFromEnum,
		Sources: []string{"audit_action.DESTROYED", "component_status.DESTROYED", "project_status.DESTROYED"},
		Note:    "Go drew — , the same glyph OrDash/StrOrDash/StampOrDash return for 'we do not know', so a destroyed cluster and an unfillable cell were the same cell. It is now the disabled tier's ◌ and the em dash means one thing again. It was briefly the middot, which collided with ui.SymbolBullet inside a picker label — one ambiguity traded for another — so the tier moved again rather than the separator, which is the older and wider convention."},
	{Status: "skipped", Tier: StatusTierDisabled, Provenance: StatusFromWire,
		Sources: []string{"a promotion gate's result (lib/promotions/gates.ts, typed in types/jsonb.types.ts as pass | fail | pending | skipped) — a JSONB field, so no enum constrains it"},
		Note:    ""},
}

// StatusTiers indexes the vocabulary by its lower-case word.
var StatusTiers = map[string]StatusTier{
	"active":           StatusTierActive,
	"online":           StatusTierActive,
	"success":          StatusTierActive,
	"succeeded":        StatusTierActive,
	"approved":         StatusTierActive,
	"ready":            StatusTierActive,
	"connected":        StatusTierActive,
	"running":          StatusTierActive,
	"queued":           StatusTierPending,
	"pending":          StatusTierPending,
	"pending_plan":     StatusTierPending,
	"pending_approval": StatusTierPending,
	"processing":       StatusTierPending,
	"claimed":          StatusTierPending,
	"provisioning":     StatusTierPending,
	"creating":         StatusTierPending,
	"updating":         StatusTierPending,
	"deploying":        StatusTierPending,
	"destroying":       StatusTierPending,
	"idle":             StatusTierIdle,
	"offline":          StatusTierIdle,
	"draining":         StatusTierIdle,
	"draft":            StatusTierIdle,
	"cancelled":        StatusTierIdle,
	"canceled":         StatusTierIdle,
	"failed":           StatusTierFailed,
	"error":            StatusTierFailed,
	"errored":          StatusTierFailed,
	"rejected":         StatusTierFailed,
	"blocked":          StatusTierFailed,
	"disabled":         StatusTierDisabled,
	"destroyed":        StatusTierDisabled,
	"skipped":          StatusTierDisabled,
}

// StatusTierOf resolves a status of any casing to its tier, falling back to StatusTierFallback.
//
// This mirrors statusTier() in packages/ui/src/status-badge.tsx, whose lookup is
// STATUS_TIER[status.toLowerCase()]. strings.ToLower and JavaScript's toLowerCase disagree on a
// handful of non-ASCII runes; every word in this vocabulary and every pgEnum value that reaches
// it is ASCII, so the two folds cannot part company on anything the product emits.
func StatusTierOf(status string) StatusTier {
	if tier, ok := StatusTiers[strings.ToLower(status)]; ok {
		return tier
	}
	return StatusTierFallback
}

// StatusGlyphOf is the glyph a terminal draws for a status of any casing.
func StatusGlyphOf(status string) string {
	return StatusGlyphs[StatusTierOf(status)]
}

// StatusGap is one value of a status-bearing enum that the vocabulary has no word for, and which
// therefore renders as StatusTierFallback on both surfaces.
type StatusGap struct {
	Enum  string
	Value string
}

// StatusVocabularyGaps is every such value, derived rather than declared: of the 71 pgEnums in the
// schema, an enum counts as status-bearing when at least one of ITS OWN values is a vocabulary
// word. The rule needs no maintenance and cannot quietly stop covering an enum, and it is
// deliberately a little over-inclusive — audit_action is here only because DESTROYED is both a
// project status and an audit verb — because a census that reports what the rule finds is worth
// more than one filtered down to what its author expected.
//
// This list is EXPECTED to be non-empty. It shrinks when somebody adds a word to
// packages/ui/src/status-badge.tsx, and it is diff-gated, so it cannot grow without a review.
var StatusVocabularyGaps = []StatusGap{
	{Enum: "alert_delivery_status", Value: "sent"},
	{Enum: "alert_delivery_status", Value: "dead"},
	{Enum: "audit_action", Value: "CREATED"},
	{Enum: "audit_action", Value: "UPDATED"},
	{Enum: "audit_action", Value: "DELETED"},
	{Enum: "audit_action", Value: "PROVISIONED"},
	{Enum: "audit_action", Value: "COMPONENT_ADDED"},
	{Enum: "audit_action", Value: "COMPONENT_UPDATED"},
	{Enum: "audit_action", Value: "COMPONENT_REMOVED"},
	{Enum: "audit_action", Value: "STATUS_CHANGED"},
	{Enum: "billing_status", Value: "none"},
	{Enum: "billing_status", Value: "trialing"},
	{Enum: "billing_status", Value: "past_due"},
	{Enum: "cloud_identity_status", Value: "testing"},
	{Enum: "cloud_identity_status", Value: "degraded"},
	{Enum: "cloud_identity_status", Value: "disconnected"},
	{Enum: "commerce_order_state", Value: "placed"},
	{Enum: "commerce_order_state", Value: "withdrawn"},
	{Enum: "commerce_order_state", Value: "refunded"},
	{Enum: "connector_health_status", Value: "healthy"},
	{Enum: "connector_status", Value: "coming_soon"},
	{Enum: "signing_key_status", Value: "pending_verification"},
	{Enum: "signing_key_status", Value: "invalid"},
	{Enum: "stripe_webhook_event_status", Value: "done"},
}
